/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDate;
import java.util.List;

/**
 * DTO class for "Aspirante"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class AspiranteDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String primerNombre ;
    private String segundoNombre ;
    private String primerApellido ;
    private String segundoApellido ;
    private int idGenero ;
    private int idResidencia ;
    private String telefono ;
    private String celular ;
    private String correoElectronico ;
    private LocalDate fechaNacimiento ;
    private int idOfertaAcademica ;
    private Integer idEstadoAspirante ;
    //--- LINKS ( RELATIONSHIPS )
    private GeneroDTO genero ; 
    private ResidenciaDTO residencia ; 
    private OfertaAcademicaDTO ofertaacademica ; 
    private EstadoAspiranteDTO estadoaspirante ; 
    private List<CorreccionDTO> correccionList ; 
    private List<DocumentoDTO> documentoList ; 
    private List<DocumentoIdentidadDTO> documentoidentidadList ; 
    private List<EtapaCompletadaDTO> etapacompletadaList ; 
    private List<TituloDTO> tituloList ; 
    private List<UsuarioAspiranteDTO> usuarioaspiranteList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Aspirante[");
		sb.append("id=").append(id);
		sb.append(separator).append("primerNombre=").append(primerNombre);
		sb.append(separator).append("segundoNombre=").append(segundoNombre);
		sb.append(separator).append("primerApellido=").append(primerApellido);
		sb.append(separator).append("segundoApellido=").append(segundoApellido);
		sb.append(separator).append("idGenero=").append(idGenero);
		sb.append(separator).append("idResidencia=").append(idResidencia);
		sb.append(separator).append("telefono=").append(telefono);
		sb.append(separator).append("celular=").append(celular);
		sb.append(separator).append("correoElectronico=").append(correoElectronico);
		sb.append(separator).append("fechaNacimiento=").append(fechaNacimiento);
		sb.append(separator).append("idOfertaAcademica=").append(idOfertaAcademica);
		sb.append(separator).append("idEstadoAspirante=").append(idEstadoAspirante);
		sb.append("]");
		return sb.toString();
	}
}
