/*
 * Created on 2026-04-30 ( 18:48:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * DTO class for "Cambiodocumento"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class CambiodocumentoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private int idDocumentoanterior ;
    private int idDocumentoactual ;
    //--- LINKS ( RELATIONSHIPS )
    private DocumentoDTO documento ; 
    private DocumentoDTO documento2 ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Cambiodocumento[");
		sb.append("id=").append(id);
		sb.append(separator).append("idDocumentoanterior=").append(idDocumentoanterior);
		sb.append(separator).append("idDocumentoactual=").append(idDocumentoactual);
		sb.append("]");
		return sb.toString();
	}
}
