/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * DTO class for "CambioDocumento"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class CambioDocumentoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private int idDocumentoCambiado ;
    private int idDocumentoActual ;
    private String motivoCambio ;
    //--- LINKS ( RELATIONSHIPS )
    private DocumentoDTO documento ; 
    private DocumentoDTO documento2 ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("CambioDocumento[");
		sb.append("id=").append(id);
		sb.append(separator).append("idDocumentoCambiado=").append(idDocumentoCambiado);
		sb.append(separator).append("idDocumentoActual=").append(idDocumentoActual);
		// attribute 'motivoCambio' (type String) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}
}
