/*
 * Created on 2026-04-26 ( 20:49:18 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;

/**
 * DTO class for "Cargo"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
@Builder
@AllArgsConstructor
public class CargoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String nombre ;
    private String descripcion ;
    private int idPrograma ;
    //--- LINKS ( RELATIONSHIPS )
    private List<AdministrativoDTO> administrativoList ; 
    private ProgramaDTO programa ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Cargo[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombre=").append(nombre);
		// attribute 'descripcion' (type String) not usable in toString() 
		sb.append(separator).append("idPrograma=").append(idPrograma);
		sb.append("]");
		return sb.toString();
	}
}
