/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDate;
import java.util.List;

/**
 * DTO class for "Cohorte"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class CohorteDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String nombre ;
    private Boolean habilitada ;
    private LocalDate fechaInicio ;
    private LocalDate fechaFin ;
    //--- LINKS ( RELATIONSHIPS )
    private List<OfertaAcademicaDTO> ofertaacademicaList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Cohorte[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombre=").append(nombre);
		sb.append(separator).append("habilitada=").append(habilitada);
		sb.append(separator).append("fechaInicio=").append(fechaInicio);
		sb.append(separator).append("fechaFin=").append(fechaFin);
		sb.append("]");
		return sb.toString();
	}
}
