/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDateTime;

/**
 * DTO class for "Correccion"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class CorreccionDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String motivoCorreccion ;
    private LocalDateTime fechaSolicitud ;
    private LocalDateTime fechaLimite ;
    private int idDocumento ;
    private int idAspirante ;
    //--- LINKS ( RELATIONSHIPS )
    private DocumentoDTO documento ; 
    private AspiranteDTO aspirante ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Correccion[");
		sb.append("id=").append(id);
		// attribute 'motivoCorreccion' (type String) not usable in toString() 
		sb.append(separator).append("fechaSolicitud=").append(fechaSolicitud);
		sb.append(separator).append("fechaLimite=").append(fechaLimite);
		sb.append(separator).append("idDocumento=").append(idDocumento);
		sb.append(separator).append("idAspirante=").append(idAspirante);
		sb.append("]");
		return sb.toString();
	}
}
