/*
 * Created on 2026-04-30 ( 19:08:00 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDate;
import java.util.List;

/**
 * DTO class for "Documento"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DocumentoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private LocalDate fechacargue ;
    private int idEstadodocumento ;
    private int idTipodocumento ;
    private int idAdministrativo ;
    private int idPlazo ;
    private int idAspirante ;
    //--- LINKS ( RELATIONSHIPS )
    private List<CambiodocumentoDTO> cambiodocumentoList ; 
    private List<CambiodocumentoDTO> cambiodocumentoList2 ; 
    private PlazoDTO plazo ; 
    private TipodocumentoDTO tipodocumento ; 
    private EstadodocumentoDTO estadodocumento ; 
    private AdministrativoDTO administrativo ; 
    private AspiranteDTO aspirante ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Documento[");
		sb.append("id=").append(id);
		sb.append(separator).append("fechacargue=").append(fechacargue);
		sb.append(separator).append("idEstadodocumento=").append(idEstadodocumento);
		sb.append(separator).append("idTipodocumento=").append(idTipodocumento);
		sb.append(separator).append("idAdministrativo=").append(idAdministrativo);
		sb.append(separator).append("idPlazo=").append(idPlazo);
		sb.append(separator).append("idAspirante=").append(idAspirante);
		sb.append("]");
		return sb.toString();
	}
}
