/*
 * Created on 2026-04-30 ( 18:48:50 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;

/**
 * DTO class for "Estado"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class EstadoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String tipo ;
    //--- LINKS ( RELATIONSHIPS )
    private List<AdministrativoDTO> administrativoList ; 
    private List<CohorteDTO> cohorteList ; 
    private List<EntrevistaDTO> entrevistaList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Estado[");
		sb.append("id=").append(id);
		sb.append(separator).append("tipo=").append(tipo);
		sb.append("]");
		return sb.toString();
	}
}
