/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDateTime;

/**
 * DTO class for "EtapaCompletada"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class EtapaCompletadaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private int idAspirante ;
    private int idTipoEtapa ;
    private LocalDateTime fecha ;
    //--- LINKS ( RELATIONSHIPS )
    private AspiranteDTO aspirante ; 
    private TipoEtapaDTO tipoetapa ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("EtapaCompletada[");
		sb.append("id=").append(id);
		sb.append(separator).append("idAspirante=").append(idAspirante);
		sb.append(separator).append("idTipoEtapa=").append(idTipoEtapa);
		sb.append(separator).append("fecha=").append(fecha);
		sb.append("]");
		return sb.toString();
	}
}
