/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;

/**
 * DTO class for "Facultad"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class FacultadDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String nombre ;
    private String correoFacultad ;
    private String nombreDecano ;
    //--- LINKS ( RELATIONSHIPS )
    private List<ProgramaPosgradoDTO> programaposgradoList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Facultad[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombre=").append(nombre);
		sb.append(separator).append("correoFacultad=").append(correoFacultad);
		sb.append(separator).append("nombreDecano=").append(nombreDecano);
		sb.append("]");
		return sb.toString();
	}
}
