/*
 * Created on 2026-04-30 ( 18:48:51 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;

/**
 * DTO class for "Modalidad"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class ModalidadDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String nombre ;
    //--- LINKS ( RELATIONSHIPS )
    private List<OfertaacademicaDTO> ofertaacademicaList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Modalidad[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombre=").append(nombre);
		sb.append("]");
		return sb.toString();
	}
}
