/*
 * Created on 2026-04-26 ( 20:49:18 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;

/**
 * DTO class for "Municipio"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
@Builder
@AllArgsConstructor
public class MunicipioDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String nombre ;
    private int idDepartamento ;
    //--- LINKS ( RELATIONSHIPS )
    private DepartamentoDTO departamento ; 
    private List<UbicacionDTO> ubicacionList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Municipio[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombre=").append(nombre);
		sb.append(separator).append("idDepartamento=").append(idDepartamento);
		sb.append("]");
		return sb.toString();
	}
}
