/*
 * Created on 2026-04-26 ( 20:49:18 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;

import java.io.Serializable;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * DTO class for "Ofertaacademica"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
@Builder
@AllArgsConstructor
public class OfertaacademicaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String encuentros ;
    private int idPrograma ;
    private int idModalidad ;
    private int idJornada ;
    //--- LINKS ( RELATIONSHIPS )
    private ProgramaDTO programa ; 
    private ModalidadDTO modalidad ; 
    private JornadaDTO jornada ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Ofertaacademica[");
		sb.append("id=").append(id);
		// attribute 'encuentros' (type String) not usable in toString() 
		sb.append(separator).append("idPrograma=").append(idPrograma);
		sb.append(separator).append("idModalidad=").append(idModalidad);
		sb.append(separator).append("idJornada=").append(idJornada);
		sb.append("]");
		return sb.toString();
	}
}
