/*
 * Created on 2026-04-24 ( 22:23:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;

/**
 * DTO class for "PersonalAdministrativo"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class PersonalAdministrativoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String nombre ;
    private String correo ;
    private String contraseña ;
    private int idCargo ;
    //--- LINKS ( RELATIONSHIPS )
    private List<DocumentoDTO> documentoList ; 
    private List<HistorialEstadoDocumentoDTO> historialestadodocumentoList ; 
    private CargoDTO cargo ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("PersonalAdministrativo[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombre=").append(nombre);
		sb.append(separator).append("correo=").append(correo);
		sb.append(separator).append("contraseña=").append(contraseña);
		sb.append(separator).append("idCargo=").append(idCargo);
		sb.append("]");
		return sb.toString();
	}
}
