/*
 * Created on 2026-04-30 ( 18:48:52 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDate;
import java.util.List;

/**
 * DTO class for "Persona"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class PersonaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String nombres ;
    private String apellidos ;
    private String correo ;
    private LocalDate fechanacimiento ;
    private String celular ;
    private String telefono ;
    private int idUbicacion ;
    private int idGenero ;
    //--- LINKS ( RELATIONSHIPS )
    private List<AdministrativoDTO> administrativoList ; 
    private List<AspiranteDTO> aspiranteList ; 
    private UbicacionDTO ubicacion ; 
    private GeneroDTO genero ; 
    private List<UsuarioDTO> usuarioList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Persona[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombres=").append(nombres);
		sb.append(separator).append("apellidos=").append(apellidos);
		sb.append(separator).append("correo=").append(correo);
		sb.append(separator).append("fechanacimiento=").append(fechanacimiento);
		sb.append(separator).append("celular=").append(celular);
		sb.append(separator).append("telefono=").append(telefono);
		sb.append(separator).append("idUbicacion=").append(idUbicacion);
		sb.append(separator).append("idGenero=").append(idGenero);
		sb.append("]");
		return sb.toString();
	}
}
