/*
 * Created on 2026-04-24 ( 22:23:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;

/**
 * DTO class for "ProgramaPosgrado"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class ProgramaPosgradoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private int codigo ;
    private String nombrePrograma ;
    private short duracionProgramaSemestres ;
    private String correoPrograma ;
    private String nombreDirector ;
    private String registroSnies ;
    private int idModalidad ;
    private int idFacultad ;
    //--- LINKS ( RELATIONSHIPS )
    private List<OfertaAcademicaDTO> ofertaacademicaList ; 
    private ModalidadDTO modalidad ; 
    private FacultadDTO facultad ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("ProgramaPosgrado[");
		sb.append("id=").append(id);
		sb.append(separator).append("codigo=").append(codigo);
		sb.append(separator).append("nombrePrograma=").append(nombrePrograma);
		sb.append(separator).append("duracionProgramaSemestres=").append(duracionProgramaSemestres);
		sb.append(separator).append("correoPrograma=").append(correoPrograma);
		sb.append(separator).append("nombreDirector=").append(nombreDirector);
		sb.append(separator).append("registroSnies=").append(registroSnies);
		sb.append(separator).append("idModalidad=").append(idModalidad);
		sb.append(separator).append("idFacultad=").append(idFacultad);
		sb.append("]");
		return sb.toString();
	}
}
