/*
 * Created on 2026-04-26 ( 20:49:18 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;

/**
 * DTO class for "Programa"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class ProgramaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private int codigo ;
    private String nombre ;
    private int semestres ;
    private String correo ;
    private String registrosnies ;
    private String nivelformacion ;
    private String titulo ;
    private String rcmineducacion ;
    private Integer creditos ;
    private String periodicidad ;
    private Float valormatricula ;
    private int idSede ;
    private int idAdministrativo ;
    private int idFacultad ;
    private int idOtros ;
    //--- LINKS ( RELATIONSHIPS )
    private List<CargoDTO> cargoList ; 
    private List<OfertaacademicaDTO> ofertaacademicaList ; 
    private SedeDTO sede ; 
    private AdministrativoDTO administrativo ; 
    private FacultadDTO facultad ; 
    private OtrosvaloresDTO otrosvalores ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Programa[");
		sb.append("id=").append(id);
		sb.append(separator).append("codigo=").append(codigo);
		sb.append(separator).append("nombre=").append(nombre);
		sb.append(separator).append("semestres=").append(semestres);
		sb.append(separator).append("correo=").append(correo);
		sb.append(separator).append("registrosnies=").append(registrosnies);
		sb.append(separator).append("nivelformacion=").append(nivelformacion);
		sb.append(separator).append("titulo=").append(titulo);
		// attribute 'rcmineducacion' (type String) not usable in toString() 
		sb.append(separator).append("creditos=").append(creditos);
		sb.append(separator).append("periodicidad=").append(periodicidad);
		sb.append(separator).append("valormatricula=").append(valormatricula);
		sb.append(separator).append("idSede=").append(idSede);
		sb.append(separator).append("idAdministrativo=").append(idAdministrativo);
		sb.append(separator).append("idFacultad=").append(idFacultad);
		sb.append(separator).append("idOtros=").append(idOtros);
		sb.append("]");
		return sb.toString();
	}
}
