/*
 * Created on 2026-04-24 ( 22:23:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;

/**
 * DTO class for "Residencia"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class ResidenciaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private int idPais ;
    private Integer idDepartamento ;
    private Integer idMunicipio ;
    private String direccion ;
    //--- LINKS ( RELATIONSHIPS )
    private List<AspiranteDTO> aspiranteList ; 
    private PaisDTO pais ; 
    private DepartamentoDTO departamento ; 
    private MunicipioDTO municipio ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Residencia[");
		sb.append("id=").append(id);
		sb.append(separator).append("idPais=").append(idPais);
		sb.append(separator).append("idDepartamento=").append(idDepartamento);
		sb.append(separator).append("idMunicipio=").append(idMunicipio);
		// attribute 'direccion' (type String) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}
}
