/*
 * Created on 2026-04-24 ( 22:23:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;

/**
 * DTO class for "TipoEtapa"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class TipoEtapaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String nombre ;
    private String descripcion ;
    //--- LINKS ( RELATIONSHIPS )
    private List<EtapaCompletadaDTO> etapacompletadaList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("TipoEtapa[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombre=").append(nombre);
		// attribute 'descripcion' (type String) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}
}
