/*
 * Created on 2026-04-30 ( 18:48:53 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;

/**
 * DTO class for "Tipodocumento"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class TipodocumentoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String nombre ;
    private String descripcion ;
    private String extension ;
    private int tamanomaximo ;
    //--- LINKS ( RELATIONSHIPS )
    private List<DocumentoDTO> documentoList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Tipodocumento[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombre=").append(nombre);
		// attribute 'descripcion' (type String) not usable in toString() 
		sb.append(separator).append("extension=").append(extension);
		sb.append(separator).append("tamanomaximo=").append(tamanomaximo);
		sb.append("]");
		return sb.toString();
	}
}
