/*
 * Created on 2026-04-24 ( 22:23:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDate;

/**
 * DTO class for "Titulo"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class TituloDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String nombreTitulo ;
    private String nombreUniversidad ;
    private LocalDate fechaGraduacion ;
    private int idTipoTitulo ;
    private int idAspirante ;
    //--- LINKS ( RELATIONSHIPS )
    private TipoTituloDTO tipotitulo ; 
    private AspiranteDTO aspirante ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Titulo[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombreTitulo=").append(nombreTitulo);
		sb.append(separator).append("nombreUniversidad=").append(nombreUniversidad);
		sb.append(separator).append("fechaGraduacion=").append(fechaGraduacion);
		sb.append(separator).append("idTipoTitulo=").append(idTipoTitulo);
		sb.append(separator).append("idAspirante=").append(idAspirante);
		sb.append("]");
		return sb.toString();
	}
}
