/*
 * Created on 2026-04-26 ( 20:49:18 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;

/**
 * DTO class for "Ubicacion"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
@Builder
@AllArgsConstructor
public class UbicacionDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String direccion ;
    private int idMunicipio ;
    //--- LINKS ( RELATIONSHIPS )
    private List<PersonaDTO> personaList ; 
    private List<SedeDTO> sedeList ; 
    private MunicipioDTO municipio ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Ubicacion[");
		sb.append("id=").append(id);
		// attribute 'direccion' (type String) not usable in toString() 
		sb.append(separator).append("idMunicipio=").append(idMunicipio);
		sb.append("]");
		return sb.toString();
	}
}
