/*
 * Created on 2026-04-24 ( 22:23:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * DTO class for "UsuarioAspirante"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class UsuarioAspiranteDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int idUsuario ;
    //--- OTHER DATA FIELDS 
    private int idAspirante ;
    //--- LINKS ( RELATIONSHIPS )
    private UsuarioDTO usuario ; 
    private AspiranteDTO aspirante ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("UsuarioAspirante[");
		sb.append("idUsuario=").append(idUsuario);
		sb.append(separator).append("idAspirante=").append(idAspirante);
		sb.append("]");
		return sb.toString();
	}
}
