/*
 * Created on 2026-04-24 ( 22:23:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;

/**
 * DTO class for "Usuario"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@NoArgsConstructor
public class UsuarioDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int id ;
    //--- OTHER DATA FIELDS 
    private String correo ;
    private String contrasena ;
    private Boolean activo ;
    private int idRol ;
    //--- LINKS ( RELATIONSHIPS )
    private RolDTO rol ; 
    private List<UsuarioAspiranteDTO> usuarioaspiranteList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Usuario[");
		sb.append("id=").append(id);
		sb.append(separator).append("correo=").append(correo);
		sb.append(separator).append("contrasena=").append(contrasena);
		sb.append(separator).append("activo=").append(activo);
		sb.append(separator).append("idRol=").append(idRol);
		sb.append("]");
		return sb.toString();
	}
}
