/*
 * Created on 2026-05-18 ( 01:57:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.AdmitidoEntity;

@Repository
public interface AdmitidoRepository extends JpaRepository<AdmitidoEntity, Integer> {

    List<AdmitidoEntity> findByIdCohorte(Integer idCohorte);

    Optional<AdmitidoEntity> findByIdCohorteAndIdAspirante(Integer idCohorte, Integer idAspirante);

    boolean existsByIdCohorteAndIdAspirante(Integer idCohorte, Integer idAspirante);
}
