/*
 * Created on 2026-05-18 ( 01:57:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.AspiranteEntity;

/**
 * Spring Data JPA repository for the AspiranteEntity entity.
 *
 * This interface extends {@link JpaRepository}, so it automatically inherits
 * standard persistence operations, including:
 * <ul>
 *   <li> Create/update entities: {@link JpaRepository#save(Object)} and {@link JpaRepository#saveAll(Iterable)}</li>
 *   <li> Basic queries: {@link JpaRepository#findById(Object)}, {@link JpaRepository#findAll()}, and {@link JpaRepository#getReferenceById(Object)}</li>
 *   <li> Validation and counting: {@link JpaRepository#existsById(Object)} and {@link JpaRepository#count()}</li>
 *   <li> Deletion: {@link JpaRepository#deleteById(Object)}, {@link JpaRepository#delete(Object)}, and {@link JpaRepository#deleteAll()}</li>
 *   <li> Paging and sorting: {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Pageable)}
 *     and {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Sort)}</li>
 * </ul>
 *
 * It can also be extended with derived query methods (findBy...),
 * following Spring Data JPA conventions.
 *
 * @category Repository
 * @version 1.0.0
 * @see JpaRepository
 * @see org.springframework.data.repository.CrudRepository
 * @see org.springframework.data.repository.PagingAndSortingRepository
 * @author a-cubica-r
 *
 */
@Repository
public interface AspiranteRepository extends JpaRepository<AspiranteEntity, Integer> {

	// Insert specific finders here

	//List<AspiranteEntity> findByXxx(String xxx);

	//List<AspiranteEntity> findByXxxStartingWith(String xxx);

	//List<AspiranteEntity> findByXxxContaining(String xxx);

	//List<AspiranteEntity> findByYyy(BigDecimal yyy);

	//List<AspiranteEntity> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);

	List<AspiranteEntity> findByDocumentoListIsNotEmpty();

	List<AspiranteEntity> findByIdCohorte(int idCohorte);

	// Aspirantes que tienen al menos un documento APROBADO por cada tipodocumento existente
	@Query("SELECT a FROM AspiranteEntity a " +
		   "WHERE NOT EXISTS (" +
		   "  SELECT td FROM TipodocumentoEntity td " +
		   "  WHERE NOT EXISTS (" +
		   "    SELECT d FROM DocumentoEntity d " +
		   "    WHERE d.aspirante = a " +
		   "      AND d.tipodocumento = td " +
		   "      AND d.estadodocumento.estado = 'APROBADO'" +
		   "  )" +
		   ")")
	List<AspiranteEntity> findValidados();

	@Query("SELECT COUNT(a) FROM AspiranteEntity a WHERE a.estado.tipo IN :tipos")
	long countByEstadoTipoIn(@Param("tipos") List<String> tipos);

	// Validados a los que les falta al menos un criterioevaluacion de su cohorte calificado
	@Query("SELECT a FROM AspiranteEntity a " +
		   "WHERE NOT EXISTS (" +
		   "  SELECT td FROM TipodocumentoEntity td " +
		   "  WHERE NOT EXISTS (" +
		   "    SELECT d FROM DocumentoEntity d " +
		   "    WHERE d.aspirante = a " +
		   "      AND d.tipodocumento = td " +
		   "      AND d.estadodocumento.estado = 'APROBADO'" +
		   "  )" +
		   ") " +
		   "AND EXISTS (" +
		   "  SELECT ce FROM CriterioevaluacionEntity ce " +
		   "  WHERE ce.idCohorte = a.idCohorte " +
		   "    AND NOT EXISTS (" +
		   "      SELECT cc FROM CalificacioncriterioEntity cc " +
		   "      WHERE cc.aspirante = a " +
		   "        AND cc.criterioevaluacion = ce " +
		   "        AND cc.puntuacion IS NOT NULL" +
		   "    )" +
		   ")")
	List<AspiranteEntity> findPorCalificar();

	// Validados con todos los criterioevaluacion de su cohorte calificados (puntuacion no nula)
	@Query("SELECT a FROM AspiranteEntity a " +
		   "WHERE NOT EXISTS (" +
		   "  SELECT td FROM TipodocumentoEntity td " +
		   "  WHERE NOT EXISTS (" +
		   "    SELECT d FROM DocumentoEntity d " +
		   "    WHERE d.aspirante = a " +
		   "      AND d.tipodocumento = td " +
		   "      AND d.estadodocumento.estado = 'APROBADO'" +
		   "  )" +
		   ") " +
		   "AND NOT EXISTS (" +
		   "  SELECT ce FROM CriterioevaluacionEntity ce " +
		   "  WHERE ce.idCohorte = a.idCohorte " +
		   "    AND NOT EXISTS (" +
		   "      SELECT cc FROM CalificacioncriterioEntity cc " +
		   "      WHERE cc.aspirante = a " +
		   "        AND cc.criterioevaluacion = ce " +
		   "        AND cc.puntuacion IS NOT NULL" +
		   "    )" +
		   ")")
	List<AspiranteEntity> findCalificados();
}
