/*
 * Created on 2026-05-18 ( 01:57:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.AspiranteEntity;

/**
 * Spring Data JPA repository for the AspiranteEntity entity.
 *
 * This interface extends {@link JpaRepository}, so it automatically inherits
 * standard persistence operations, including:
 * <ul>
 *   <li> Create/update entities: {@link JpaRepository#save(Object)} and {@link JpaRepository#saveAll(Iterable)}</li>
 *   <li> Basic queries: {@link JpaRepository#findById(Object)}, {@link JpaRepository#findAll()}, and {@link JpaRepository#getReferenceById(Object)}</li>
 *   <li> Validation and counting: {@link JpaRepository#existsById(Object)} and {@link JpaRepository#count()}</li>
 *   <li> Deletion: {@link JpaRepository#deleteById(Object)}, {@link JpaRepository#delete(Object)}, and {@link JpaRepository#deleteAll()}</li>
 *   <li> Paging and sorting: {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Pageable)}
 *     and {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Sort)}</li>
 * </ul>
 *
 * It can also be extended with derived query methods (findBy...),
 * following Spring Data JPA conventions.
 *
 * @category Repository
 * @version 1.0.0
 * @see JpaRepository
 * @see org.springframework.data.repository.CrudRepository
 * @see org.springframework.data.repository.PagingAndSortingRepository
 * @author a-cubica-r
 *
 */
@Repository
public interface AspiranteRepository extends JpaRepository<AspiranteEntity, Integer> {

	Optional<AspiranteEntity> findFirstByIdPersona(Integer idPersona);

	@Query("SELECT a.id FROM AspiranteEntity a WHERE a.idPersona = :idPersona")
	Optional<Integer> findIdByIdPersona(@Param("idPersona") Integer idPersona);

	@Query("SELECT a.estado.tipo FROM AspiranteEntity a WHERE a.id = :id")
	Optional<String> findEstadoTipoById(@Param("id") Integer id);

	@Query("SELECT a.idCohorte FROM AspiranteEntity a WHERE a.id = :id")
	Optional<Integer> findIdCohorteById(@Param("id") Integer id);

	@Query("SELECT a.puntuacion FROM AspiranteEntity a WHERE a.id = :id")
	Optional<java.math.BigDecimal> findPuntuacionById(@Param("id") Integer id);

	List<AspiranteEntity> findByDocumentoListIsNotEmpty();

	List<AspiranteEntity> findByIdCohorte(int idCohorte);

	long countByIdCohorte(Integer idCohorte);

	@Query("SELECT COUNT(a) FROM AspiranteEntity a WHERE a.idCohorte = :cohorteId AND a.estado.tipo IN :tipos")
	long countByIdCohorteAndEstadoTipoIn(@Param("cohorteId") Integer cohorteId, @Param("tipos") List<String> tipos);

	// Aspirantes con todos los documentos requeridos por su cohorte en estado APROBADO
	@Query("SELECT a FROM AspiranteEntity a " +
		   "WHERE NOT EXISTS (" +
		   "  SELECT drcc FROM DocumentosrequisitoconsejocohorteEntity drcc " +
		   "  WHERE drcc.idCohorte = a.idCohorte " +
		   "    AND NOT EXISTS (" +
		   "      SELECT d FROM DocumentoEntity d " +
		   "      WHERE d.aspirante = a " +
		   "        AND d.documentosrequisitoconsejocohorte = drcc " +
		   "        AND d.estadodocumento.estado = 'APROBADO'" +
		   "    )" +
		   ") " +
		   "AND NOT EXISTS (" +
		   "  SELECT drpc FROM DocumentosrequisitoprogramacohorteEntity drpc " +
		   "  WHERE drpc.idCohorte = a.idCohorte " +
		   "    AND NOT EXISTS (" +
		   "      SELECT d FROM DocumentoEntity d " +
		   "      WHERE d.aspirante = a " +
		   "        AND d.documentosrequisitoprogramacohorte = drpc " +
		   "        AND d.estadodocumento.estado = 'APROBADO'" +
		   "    )" +
		   ")")
	List<AspiranteEntity> findValidados();

	@Query("SELECT COUNT(a) FROM AspiranteEntity a WHERE a.estado.tipo IN :tipos")
	long countByEstadoTipoIn(@Param("tipos") List<String> tipos);

	// Validados a los que les falta al menos un criteriocohorte de su cohorte calificado
	@Query("SELECT a FROM AspiranteEntity a " +
		   "WHERE NOT EXISTS (" +
		   "  SELECT drcc FROM DocumentosrequisitoconsejocohorteEntity drcc " +
		   "  WHERE drcc.idCohorte = a.idCohorte " +
		   "    AND NOT EXISTS (" +
		   "      SELECT d FROM DocumentoEntity d " +
		   "      WHERE d.aspirante = a " +
		   "        AND d.documentosrequisitoconsejocohorte = drcc " +
		   "        AND d.estadodocumento.estado = 'APROBADO'" +
		   "    )" +
		   ") " +
		   "AND NOT EXISTS (" +
		   "  SELECT drpc FROM DocumentosrequisitoprogramacohorteEntity drpc " +
		   "  WHERE drpc.idCohorte = a.idCohorte " +
		   "    AND NOT EXISTS (" +
		   "      SELECT d FROM DocumentoEntity d " +
		   "      WHERE d.aspirante = a " +
		   "        AND d.documentosrequisitoprogramacohorte = drpc " +
		   "        AND d.estadodocumento.estado = 'APROBADO'" +
		   "    )" +
		   ") " +
		   "AND EXISTS (" +
		   "  SELECT ccCohorte FROM CriteriocohorteEntity ccCohorte " +
		   "  WHERE ccCohorte.idCohorte = a.idCohorte " +
		   "    AND NOT EXISTS (" +
		   "      SELECT cal FROM CalificacioncriterioEntity cal " +
		   "      WHERE cal.aspirante = a " +
		   "        AND cal.criteriocohorte = ccCohorte " +
		   "        AND cal.puntuacion IS NOT NULL" +
		   "    )" +
		   ")")
	List<AspiranteEntity> findPorCalificar();

	// Validados con todos los criteriocohorte de su cohorte calificados (puntuacion no nula)
	@Query("SELECT a FROM AspiranteEntity a " +
		   "WHERE NOT EXISTS (" +
		   "  SELECT drcc FROM DocumentosrequisitoconsejocohorteEntity drcc " +
		   "  WHERE drcc.idCohorte = a.idCohorte " +
		   "    AND NOT EXISTS (" +
		   "      SELECT d FROM DocumentoEntity d " +
		   "      WHERE d.aspirante = a " +
		   "        AND d.documentosrequisitoconsejocohorte = drcc " +
		   "        AND d.estadodocumento.estado = 'APROBADO'" +
		   "    )" +
		   ") " +
		   "AND NOT EXISTS (" +
		   "  SELECT drpc FROM DocumentosrequisitoprogramacohorteEntity drpc " +
		   "  WHERE drpc.idCohorte = a.idCohorte " +
		   "    AND NOT EXISTS (" +
		   "      SELECT d FROM DocumentoEntity d " +
		   "      WHERE d.aspirante = a " +
		   "        AND d.documentosrequisitoprogramacohorte = drpc " +
		   "        AND d.estadodocumento.estado = 'APROBADO'" +
		   "    )" +
		   ") " +
		   "AND NOT EXISTS (" +
		   "  SELECT ccCohorte FROM CriteriocohorteEntity ccCohorte " +
		   "  WHERE ccCohorte.idCohorte = a.idCohorte " +
		   "    AND NOT EXISTS (" +
		   "      SELECT cal FROM CalificacioncriterioEntity cal " +
		   "      WHERE cal.aspirante = a " +
		   "        AND cal.criteriocohorte = ccCohorte " +
		   "        AND cal.puntuacion IS NOT NULL" +
		   "    )" +
		   ")")
	List<AspiranteEntity> findCalificados();
}
