/*
 * Created on 2026-05-13 ( 00:00:00 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.CalificacioncriterioEntity;

/**
 * Spring Data JPA repository for the CalificacioncriterioEntity entity.
 *
 * @category Repository
 * @version 1.0.0
 * @see JpaRepository
 * @author a-cubica-r
 *
 */
@Repository
public interface CalificacioncriterioRepository extends JpaRepository<CalificacioncriterioEntity, Integer> {

    List<CalificacioncriterioEntity> findByIdAspirante(Integer idAspirante);

    List<CalificacioncriterioEntity> findByIdCriterio(Integer idCriterio);

    Optional<CalificacioncriterioEntity> findByIdAspiranteAndIdCriterio(Integer idAspirante, Integer idCriterio);

    boolean existsByIdAspiranteAndIdCriterio(Integer idAspirante, Integer idCriterio);
}
