/*
 * Created on 2026-05-18 ( 01:57:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.CohorteEntity;

/**
 * Spring Data JPA repository for the CohorteEntity entity.
 *
 * This interface extends {@link JpaRepository}, so it automatically inherits
 * standard persistence operations, including:
 * <ul>
 * <li>Create/update entities: {@link JpaRepository#save(Object)} and
 * {@link JpaRepository#saveAll(Iterable)}</li>
 * <li>Basic queries: {@link JpaRepository#findById(Object)},
 * {@link JpaRepository#findAll()}, and
 * {@link JpaRepository#getReferenceById(Object)}</li>
 * <li>Validation and counting: {@link JpaRepository#existsById(Object)} and
 * {@link JpaRepository#count()}</li>
 * <li>Deletion: {@link JpaRepository#deleteById(Object)},
 * {@link JpaRepository#delete(Object)}, and
 * {@link JpaRepository#deleteAll()}</li>
 * <li>Paging and sorting:
 * {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Pageable)}
 * and
 * {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Sort)}</li>
 * </ul>
 *
 * It can also be extended with derived query methods (findBy...),
 * following Spring Data JPA conventions.
 *
 * @category Repository
 * @version 1.0.0
 * @see JpaRepository
 * @see org.springframework.data.repository.CrudRepository
 * @see org.springframework.data.repository.PagingAndSortingRepository
 * @author a-cubica-r
 *
 */
@Repository
public interface CohorteRepository extends JpaRepository<CohorteEntity, Integer> {

	@Query(value = """
		SELECT COUNT(a.id)
		FROM aspirante a
		INNER JOIN estado ea ON a.id_estado = ea.id
		INNER JOIN cohorte c ON a.id_cohorte = c.id
		INNER JOIN estado ec ON c.id_estado = ec.id
		WHERE a.id_cohorte = :cohorteId
		AND ea.entidad = 'aspirante'
		AND ea.tipo = 'EN PROCESO'
		AND ec.entidad = 'cohorte'
		AND ec.tipo = 'ABIERTA'
		""", nativeQuery = true)
	long countAspirantesEnProcesoEnCohorteAbierta(@Param("cohorteId") Integer cohorteId);

	@Query("SELECT c FROM CohorteEntity c WHERE c.idPrograma = :programaId AND c.estado.tipo = 'ABIERTA'")
	Optional<CohorteEntity> findActiveByIdPrograma(@Param("programaId") Integer programaId);

	List<CohorteEntity> findByIdPrograma(Integer idPrograma);

	@Query("SELECT c FROM CohorteEntity c WHERE c.idPrograma = :idPrograma AND c.estado.entidad = 'cohorte' AND c.estado.tipo = 'ABIERTA'")
	List<CohorteEntity> findActivasByIdPrograma(@Param("idPrograma") Integer idPrograma);

	@Query(value = """
		SELECT COUNT(a.id)
		FROM aspirante a
		INNER JOIN estado ea ON a.id_estado = ea.id
		WHERE a.id_cohorte = :cohorteId
		AND ea.entidad = 'aspirante'
		AND ea.tipo = 'EN PROCESO'
		""", nativeQuery = true)
	long countAspirantesEnProcesoByCohorteId(@Param("cohorteId") Integer cohorteId);

	// Insert specific finders here

	// List<CohorteEntity> findByXxx(String xxx);

	// List<CohorteEntity> findByXxxStartingWith(String xxx);

	// List<CohorteEntity> findByXxxContaining(String xxx);

	// List<CohorteEntity> findByYyy(BigDecimal yyy);

	// List<CohorteEntity> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
