/*
 * Created on 2026-05-24 ( 03:25:12 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import org.springframework.data.jpa.repository.*;
import org.springframework.data.repository.query.*;
import org.springframework.stereotype.*;

import ufps.edu.co.persistence.entities.*;
import ufps.edu.co.persistence.projections.*;

/**
 * Spring Data JPA repository for the CriteriocohorteEntity entity.
 *
 * This interface extends {@link JpaRepository}, so it automatically inherits
 * standard persistence operations, including:
 * <ul>
 *   <li> Create/update entities: {@link JpaRepository#save(Object)} and {@link JpaRepository#saveAll(Iterable)}</li>
 *   <li> Basic queries: {@link JpaRepository#findById(Object)}, {@link JpaRepository#findAll()}, and {@link JpaRepository#getReferenceById(Object)}</li>
 *   <li> Validation and counting: {@link JpaRepository#existsById(Object)} and {@link JpaRepository#count()}</li>
 *   <li> Deletion: {@link JpaRepository#deleteById(Object)}, {@link JpaRepository#delete(Object)}, and {@link JpaRepository#deleteAll()}</li>
 *   <li> Paging and sorting: {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Pageable)}
 *     and {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Sort)}</li>
 * </ul>
 *
 * It can also be extended with derived query methods (findBy...),
 * following Spring Data JPA conventions.
 *
 * @category Repository
 * @version 1.0.0
 * @see JpaRepository
 * @see org.springframework.data.repository.CrudRepository
 * @see org.springframework.data.repository.PagingAndSortingRepository
 * @author a-cubica-r
 *
 */
@Repository
public interface CriteriocohorteRepository extends JpaRepository<CriteriocohorteEntity, Integer> {

	java.util.List<CriteriocohorteEntity> findByIdCohorte(Integer idCohorte);

	java.util.List<CriteriocohorteEntity> findByIdCriterio(Integer idCriterio);

	@Query("SELECT cc.id AS id, cc.pesoSnapshot AS pesoSnapshot, ce.nombre AS nombreCriterio, cal.puntuacion AS puntajeObtenido " +
		   "FROM CriteriocohorteEntity cc " +
		   "LEFT JOIN cc.criterioevaluacion ce " +
		   "LEFT JOIN cc.calificacioncriterioList cal ON cal.idAspirante = :idAspirante " +
		   "WHERE cc.idCohorte = :idCohorte")
	java.util.List<CriterioCalificacionView> findCriteriosConCalificacion(
		@Param("idCohorte") Integer idCohorte,
		@Param("idAspirante") Integer idAspirante);

	// Insert specific finders here

	//List<CriteriocohorteEntity> findByXxx(String xxx);

	//List<CriteriocohorteEntity> findByXxxStartingWith(String xxx);

	//List<CriteriocohorteEntity> findByXxxContaining(String xxx);

	//List<CriteriocohorteEntity> findByYyy(BigDecimal yyy);

	//List<CriteriocohorteEntity> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
