/*
 * Created on 2026-05-24 ( 17:03:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.DocumentosrequisitoconsejocohorteEntity;

@Repository
public interface DocumentosrequisitoconsejocohorteRepository extends JpaRepository<DocumentosrequisitoconsejocohorteEntity, Integer> {

	List<DocumentosrequisitoconsejocohorteEntity> findByIdCohorte(Integer idCohorte);
}
