/*
 * Created on 2026-05-24 ( 17:03:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.DocumentosrequisitoconsejoEntity;

@Repository
public interface DocumentosrequisitoconsejoRepository extends JpaRepository<DocumentosrequisitoconsejoEntity, Integer> {

    @Query("SELECT DISTINCT d FROM DocumentosrequisitoconsejoEntity d JOIN d.documentosrequisitoconsejocohorteList dc JOIN dc.cohorte c WHERE c.idPrograma = :idPrograma")
    List<DocumentosrequisitoconsejoEntity> findByIdPrograma(@Param("idPrograma") Integer idPrograma);
}
