/*
 * Created on 2026-05-24 ( 17:03:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.DocumentoEntity;

@Repository
public interface DocumentoRepository extends JpaRepository<DocumentoEntity, Integer> {

	@Query("SELECT d.id, d.enlaceurl, d.fechacargue, d.keyfile, d.observaciones, " +
		   "d.idAdministrativo, d.idAspirante, d.idEstadodocumento, d.idPlazo, " +
		   "d.idDocumentosrequisitoconsejocohorte, d.idDocumentosrequisitoprogramacohorte, " +
		   "ed.estado " +
		   "FROM DocumentoEntity d LEFT JOIN d.estadodocumento ed")
	List<Object[]> findAllScalar();

	@Query("SELECT d.id, d.enlaceurl, d.fechacargue, d.keyfile, d.observaciones, " +
		   "d.idAdministrativo, d.idAspirante, d.idEstadodocumento, d.idPlazo, " +
		   "d.idDocumentosrequisitoconsejocohorte, d.idDocumentosrequisitoprogramacohorte, " +
		   "ed.estado " +
		   "FROM DocumentoEntity d LEFT JOIN d.estadodocumento ed WHERE d.id = :id")
	Optional<Object[]> findByIdScalar(@Param("id") Integer id);

	@Query("SELECT d.id, d.enlaceurl, d.fechacargue, d.keyfile, d.observaciones, " +
		   "d.idAdministrativo, d.idAspirante, d.idEstadodocumento, d.idPlazo, " +
		   "d.idDocumentosrequisitoconsejocohorte, d.idDocumentosrequisitoprogramacohorte, " +
		   "ed.estado " +
		   "FROM DocumentoEntity d LEFT JOIN d.estadodocumento ed WHERE d.idAspirante = :idAspirante")
	List<Object[]> findByIdAspiranteScalar(@Param("idAspirante") Integer idAspirante);

	@Query("SELECT d.id, d.enlaceurl, d.fechacargue, d.keyfile, d.observaciones, " +
		   "d.idAdministrativo, d.idAspirante, d.idEstadodocumento, d.idPlazo, " +
		   "d.idDocumentosrequisitoconsejocohorte, d.idDocumentosrequisitoprogramacohorte, " +
		   "ed.estado " +
		   "FROM DocumentoEntity d LEFT JOIN d.estadodocumento ed " +
		   "WHERE d.idAspirante = :idAspirante AND d.idDocumentosrequisitoconsejocohorte = :idDocReqConsejoCohorte")
	Optional<Object[]> findByIdAspiranteAndIdDocumentosrequisitoconsejocohorteScalar(
		@Param("idAspirante") Integer idAspirante,
		@Param("idDocReqConsejoCohorte") Integer idDocumentosrequisitoconsejocohorte);

	@Query("SELECT d.id, d.enlaceurl, d.fechacargue, d.keyfile, d.observaciones, " +
		   "d.idAdministrativo, d.idAspirante, d.idEstadodocumento, d.idPlazo, " +
		   "d.idDocumentosrequisitoconsejocohorte, d.idDocumentosrequisitoprogramacohorte, " +
		   "ed.estado " +
		   "FROM DocumentoEntity d LEFT JOIN d.estadodocumento ed " +
		   "WHERE d.idAspirante = :idAspirante AND d.idDocumentosrequisitoprogramacohorte = :idDocReqProgramaCohorte")
	Optional<Object[]> findByIdAspiranteAndIdDocumentosrequisitoprogramacohorteScalar(
		@Param("idAspirante") Integer idAspirante,
		@Param("idDocReqProgramaCohorte") Integer idDocumentosrequisitoprogramacohorte);
}
