/*
 * Created on 2026-05-18 ( 01:57:51 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.EntrevistaEntity;

@Repository
public interface EntrevistaRepository extends JpaRepository<EntrevistaEntity, Integer> {

	@Query("SELECT e.id, e.fecha, e.tiempo, e.motivocambio, " +
		   "e.idAspirante, e.idEstado, e.idTipoentrevista, e.idUbicacion, " +
		   "est.tipo, est.entidad, t.tipo, t.descripcion, u.direccion " +
		   "FROM EntrevistaEntity e " +
		   "LEFT JOIN e.estado est LEFT JOIN e.tipoentrevista t LEFT JOIN e.ubicacion u")
	List<Object[]> findAllScalar();

	@Query("SELECT e.id, e.fecha, e.tiempo, e.motivocambio, " +
		   "e.idAspirante, e.idEstado, e.idTipoentrevista, e.idUbicacion, " +
		   "est.tipo, est.entidad, t.tipo, t.descripcion, u.direccion " +
		   "FROM EntrevistaEntity e " +
		   "LEFT JOIN e.estado est LEFT JOIN e.tipoentrevista t LEFT JOIN e.ubicacion u " +
		   "WHERE e.id = :id")
	Optional<Object[]> findByIdScalar(@Param("id") Integer id);

	@Query("SELECT e.id, e.fecha, e.tiempo, e.motivocambio, " +
		   "e.idAspirante, e.idEstado, e.idTipoentrevista, e.idUbicacion, " +
		   "est.tipo, est.entidad, t.tipo, t.descripcion, u.direccion " +
		   "FROM EntrevistaEntity e " +
		   "LEFT JOIN e.estado est LEFT JOIN e.tipoentrevista t LEFT JOIN e.ubicacion u " +
		   "WHERE e.idAspirante = :idAspirante")
	List<Object[]> findByIdAspiranteScalar(@Param("idAspirante") Integer idAspirante);
}
