/*
 * Created on 2026-05-18 ( 01:57:52 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.ModalidadEntity;

@Repository
public interface ModalidadRepository extends JpaRepository<ModalidadEntity, Integer> {

    Optional<ModalidadEntity> findByNombreIgnoreCase(String nombre);

}
