/*
 * Created on 2026-05-18 ( 01:57:53 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.PagoEntity;
import ufps.edu.co.rest.dto.PagoResumenDTO;

/**
 * Spring Data JPA repository for the PagoEntity entity.
 *
 * This interface extends {@link JpaRepository}, so it automatically inherits
 * standard persistence operations, including:
 * <ul>
 *   <li> Create/update entities: {@link JpaRepository#save(Object)} and {@link JpaRepository#saveAll(Iterable)}</li>
 *   <li> Basic queries: {@link JpaRepository#findById(Object)}, {@link JpaRepository#findAll()}, and {@link JpaRepository#getReferenceById(Object)}</li>
 *   <li> Validation and counting: {@link JpaRepository#existsById(Object)} and {@link JpaRepository#count()}</li>
 *   <li> Deletion: {@link JpaRepository#deleteById(Object)}, {@link JpaRepository#delete(Object)}, and {@link JpaRepository#deleteAll()}</li>
 *   <li> Paging and sorting: {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Pageable)}
 *     and {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Sort)}</li>
 * </ul>
 *
 * It can also be extended with derived query methods (findBy...),
 * following Spring Data JPA conventions.
 *
 * @category Repository
 * @version 1.0.0
 * @see JpaRepository
 * @see org.springframework.data.repository.CrudRepository
 * @see org.springframework.data.repository.PagingAndSortingRepository
 * @author a-cubica-r
 *
 */
@Repository
public interface PagoRepository extends JpaRepository<PagoEntity, Integer> {

	List<PagoEntity> findByIdAspirante(Integer idAspirante);

	@Query("select new ufps.edu.co.rest.dto.PagoResumenDTO("
			+ "p.id, "
			+ "p.idAspirante, "
			+ "p.idEstado, "
			+ "p.idPagoconcepto, "
			+ "concat(coalesce(per.nombres, ''), concat(' ', coalesce(per.apellidos, ''))), "
			+ "e.tipo, "
			+ "pc.id, "
			+ "pc.tipo) "
			+ "from PagoEntity p "
			+ "join p.aspirante a "
			+ "join a.persona per "
			+ "join p.estado e "
			+ "join p.pagoconcepto pc "
			+ "where p.idAspirante = :idAspirante "
			+ "order by p.id")
	List<PagoResumenDTO> findResumenByIdAspirante(@Param("idAspirante") Integer idAspirante);

}
