/*
 * Created on 2026-05-18 ( 01:57:54 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.ProgramaEntity;

@Repository
public interface ProgramaRepository extends JpaRepository<ProgramaEntity, Integer> {

	@Query("SELECT p FROM ProgramaEntity p LEFT JOIN FETCH p.facultad LEFT JOIN FETCH p.sede sede LEFT JOIN FETCH sede.ubicacion LEFT JOIN FETCH p.otrosvalores LEFT JOIN FETCH p.tiporegistro WHERE p.idFacultad = :idFacultad")
	List<ProgramaEntity> findByIdFacultad(@Param("idFacultad") Integer idFacultad);
}
