/*
 * Created on 2026-05-18 ( 01:57:55 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.SemestreEntity;

/**
 * Spring Data JPA repository for the SemestreEntity entity.
 *
 * This interface extends {@link JpaRepository}, so it automatically inherits
 * standard persistence operations, including:
 * <ul>
 *   <li> Create/update entities: {@link JpaRepository#save(Object)} and {@link JpaRepository#saveAll(Iterable)}</li>
 *   <li> Basic queries: {@link JpaRepository#findById(Object)}, {@link JpaRepository#findAll()}, and {@link JpaRepository#getReferenceById(Object)}</li>
 *   <li> Validation and counting: {@link JpaRepository#existsById(Object)} and {@link JpaRepository#count()}</li>
 *   <li> Deletion: {@link JpaRepository#deleteById(Object)}, {@link JpaRepository#delete(Object)}, and {@link JpaRepository#deleteAll()}</li>
 *   <li> Paging and sorting: {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Pageable)}
 *     and {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Sort)}</li>
 * </ul>
 *
 * It can also be extended with derived query methods (findBy...),
 * following Spring Data JPA conventions.
 *
 * @category Repository
 * @version 1.0.0
 * @see JpaRepository
 * @see org.springframework.data.repository.CrudRepository
 * @see org.springframework.data.repository.PagingAndSortingRepository
 * @author a-cubica-r
 *
 */
@Repository
public interface SemestreRepository extends JpaRepository<SemestreEntity, Integer> {

	@Query("SELECT s.id, s.nombre, s.fechaInicio, s.fechaFin, s.idEstado, s.estado.id, s.estado.entidad, s.estado.tipo FROM SemestreEntity s")
	List<Object[]> findAllScalar();

	@Query("SELECT s.id, s.nombre, s.fechaInicio, s.fechaFin, s.idEstado, s.estado.id, s.estado.entidad, s.estado.tipo FROM SemestreEntity s WHERE s.id = :id")
	Optional<Object[]> findByIdScalar(@Param("id") Integer id);

	// Insert specific finders here

	//List<SemestreEntity> findByXxx(String xxx);

	//List<SemestreEntity> findByXxxStartingWith(String xxx);

	//List<SemestreEntity> findByXxxContaining(String xxx);

	//List<SemestreEntity> findByYyy(BigDecimal yyy);

	//List<SemestreEntity> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
