/*
 * Created on 2026-05-18 ( 01:57:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDate;

/**
 * DTO class for "Admitido"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AdmitidoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private LocalDate fechageneracion ;
    private Integer idCohorte ;
    private Integer idAspirante ;
    //--- LINKS ( RELATIONSHIPS )
    private AspiranteDTO aspirante ; 
    private CohorteDTO cohorte ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Admitido[");
		sb.append("id=").append(id);
		sb.append(separator).append("fechageneracion=").append(fechageneracion);
		sb.append(separator).append("idCohorte=").append(idCohorte);
		sb.append(separator).append("idAspirante=").append(idAspirante);
		sb.append("]");
		return sb.toString();
	}
}
