/*
 * Created on 2026-05-14 ( 22:04:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDate;
import java.util.List;

/**
 * DTO class for "Administrativo"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AdministrativoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private LocalDate fechainicio ;
    private LocalDate fechasalida ;
    private Integer idCargo ;
    private Integer idEstado ;
    private Integer idPersona ;
    //--- LINKS ( RELATIONSHIPS )
    private CargoDTO cargo ; 
    private EstadoDTO estado ; 
    private PersonaDTO persona ; 
    private List<DocumentoDTO> documentoList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Administrativo[");
		sb.append("id=").append(id);
		sb.append(separator).append("fechainicio=").append(fechainicio);
		sb.append(separator).append("fechasalida=").append(fechasalida);
		sb.append(separator).append("idCargo=").append(idCargo);
		sb.append(separator).append("idEstado=").append(idEstado);
		sb.append(separator).append("idPersona=").append(idPersona);
		sb.append("]");
		return sb.toString();
	}
}
