/*
 * Created on 2026-05-14 ( 22:04:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.math.BigDecimal;
import java.util.List;

/**
 * DTO class for "Aspirante"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AspiranteDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private BigDecimal puntuacion ;
    private Integer idCohorte ;
    private Integer idEstado ;
    private Integer idPersona ;
    private Integer idTipovinculacion ;
    //--- LINKS ( RELATIONSHIPS )
    private PersonaDTO persona ; 
    private EstadoDTO estado ; 
    private CohorteDTO cohorte ; 
    private TipovinculacionDTO tipovinculacion ; 
    private List<CalificacioncriterioDTO> calificacioncriterioList ; 
    private List<DocumentoDTO> documentoList ; 
    private List<EntrevistaDTO> entrevistaList ; 
    private List<ListaadmitidosDTO> listaadmitidosList ; 
    private List<PagoDTO> pagoList ; 
    private List<PagoDTO> pagosList ; 
    private List<ResultadopruebaDTO> resultadopruebaList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Aspirante[");
		sb.append("id=").append(id);
		sb.append(separator).append("puntuacion=").append(puntuacion);
		sb.append(separator).append("idCohorte=").append(idCohorte);
		sb.append(separator).append("idEstado=").append(idEstado);
		sb.append(separator).append("idPersona=").append(idPersona);
		sb.append(separator).append("idTipovinculacion=").append(idTipovinculacion);
		sb.append("]");
		return sb.toString();
	}
}
