/*
 * Created on 2026-05-24 ( 15:03:10 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.math.BigDecimal;

/**
 * DTO class for "Calificacioncriterio"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CalificacioncriterioDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private BigDecimal puntuacion ;
    private Integer idAspirante ;
    private Integer idCriteriocohorte ;
    //--- LINKS ( RELATIONSHIPS )
    private AspiranteDTO aspirante ; 
    private CriteriocohorteDTO criteriocohorte ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Calificacioncriterio[");
		sb.append("id=").append(id);
		sb.append(separator).append("puntuacion=").append(puntuacion);
		sb.append(separator).append("idAspirante=").append(idAspirante);
		sb.append(separator).append("idCriteriocohorte=").append(idCriteriocohorte);
		sb.append("]");
		return sb.toString();
	}
}
