/*
 * Created on 2026-05-13 ( 00:00:00 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.math.BigDecimal;

/**
 * DTO class for "Calificacioncriterio"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CalificacioncriterioDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY
    private Integer id;
    //--- OTHER DATA FIELDS
    private Integer idAspirante;
    private Integer idCriterio;
    private BigDecimal puntuacion;
    private BigDecimal pesoSnapshot;
    private String observaciones;
    //--- LINKS ( RELATIONSHIPS )
    private AspiranteDTO aspirante;
    private CriterioaceptacionDTO criterioaceptacion;

    @Override
    public String toString() {
        String separator = "|";
        StringBuilder sb = new StringBuilder();
        sb.append("Calificacioncriterio[");
        sb.append("id=").append(id);
        sb.append(separator).append("idAspirante=").append(idAspirante);
        sb.append(separator).append("idCriterio=").append(idCriterio);
        sb.append(separator).append("puntuacion=").append(puntuacion);
        sb.append(separator).append("pesoSnapshot=").append(pesoSnapshot);
        // attribute 'observaciones' (type String/TEXT) not usable in toString()
        sb.append("]");
        return sb.toString();
    }
}
