/*
 * Created on 2026-05-14 ( 22:37:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.util.List;

/**
 * DTO class for "Clave"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ClaveDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String valor ;
    //--- LINKS ( RELATIONSHIPS )
    private List<UsuarioDTO> usuarioList ; 

    @Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("Clave[");
		sb.append("id=").append(id);
		// attribute 'valor' (type String) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}
}
