/*
 * Created on 2026-05-14 ( 22:37:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.util.List;

/**
 * DTO class for "Cohorte"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CohorteDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String nombre ;
    private int cupos ;
    private boolean requiereentrevista ;
    private boolean requiereprueba ;
    private int idEstado ;
    private int idSemestre ;
    private int idModalidad ;
    private int idPlazodocumentacion ;
    private int idPlazoinscripcion ;
    private int idPlazopago ;
    private int idPrograma ;
    //--- LINKS ( RELATIONSHIPS )
    private List<AspiranteDTO> aspiranteList ; 
    private EstadoDTO estado ; 
    private SemestreDTO semestre ; 
    private ModalidadDTO modalidad ; 
    private PlazoDTO plazo ; 
    private PlazoDTO plazo2 ; 
    private PlazoDTO plazo3 ; 
    private ProgramaDTO programa ; 
    private List<CriterioaceptacionDTO> criterioaceptacionList ; 
    private List<ListaadmitidosDTO> listaadmitidosList ; 
    private List<PruebaDTO> pruebaList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Cohorte[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombre=").append(nombre);
		sb.append(separator).append("cupos=").append(cupos);
		sb.append(separator).append("requiereentrevista=").append(requiereentrevista);
		sb.append(separator).append("requiereprueba=").append(requiereprueba);
		sb.append(separator).append("idEstado=").append(idEstado);
		sb.append(separator).append("idSemestre=").append(idSemestre);
		sb.append(separator).append("idModalidad=").append(idModalidad);
		sb.append(separator).append("idPlazodocumentacion=").append(idPlazodocumentacion);
		sb.append(separator).append("idPlazoinscripcion=").append(idPlazoinscripcion);
		sb.append(separator).append("idPlazopago=").append(idPlazopago);
		sb.append(separator).append("idPrograma=").append(idPrograma);
		sb.append("]");
		return sb.toString();
	}
}
