/*
 * Created on 2026-05-18 ( 01:57:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.math.BigDecimal;
import java.util.List;

/**
 * DTO class for "Criterioevaluacion"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CriterioevaluacionDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String nombre ;
    private Boolean activo ;
    private String descripcion ;
    private BigDecimal peso ;
    private Integer idprograma ;
    //--- LINKS ( RELATIONSHIPS )
    private List<CalificacioncriterioDTO> calificacioncriterioList ; 
    private ProgramaDTO programa ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Criterioevaluacion[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombre=").append(nombre);
		sb.append(separator).append("activo=").append(activo);
		// attribute 'descripcion' (type String) not usable in toString() 
		sb.append(separator).append("peso=").append(peso);
		sb.append(separator).append("idPrograma=").append(idprograma);
		sb.append("]");
		return sb.toString();
	}
}
