/*
 * Created on 2026-05-18 ( 01:57:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.util.List;

/**
 * DTO class for "Discapacidad"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DiscapacidadDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String tipodiscapacidad ;
    //--- LINKS ( RELATIONSHIPS )
    private List<PersonaDTO> personaList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Discapacidad[");
		sb.append("id=").append(id);
		sb.append(separator).append("tipodiscapacidad=").append(tipodiscapacidad);
		sb.append("]");
		return sb.toString();
	}
}
