/*
 * Created on 2026-05-14 ( 22:37:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * DTO class for "Documentopersona"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DocumentopersonaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private int numerodocumento ;
    private int idTipodocumento ;
    private int idLugarexpedicion ;
    //--- LINKS ( RELATIONSHIPS )
    private TipodocumentoDTO tipodocumento ; 
    private UbicacionDTO ubicacion ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Documentopersona[");
		sb.append("id=").append(id);
		sb.append(separator).append("numerodocumento=").append(numerodocumento);
		sb.append(separator).append("idTipodocumento=").append(idTipodocumento);
		sb.append(separator).append("idLugarexpedicion=").append(idLugarexpedicion);
		sb.append("]");
		return sb.toString();
	}
}
