/*
 * Created on 2026-05-24 ( 03:29:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * DTO class for "Documentosrequisitoconcejocohorte"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DocumentosrequisitoconcejocohorteDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private Integer idDocrequisito ;
    private Integer idCohorte ;
    //--- LINKS ( RELATIONSHIPS )
    private CohorteDTO cohorte ; 
    private DocumentosrequisitoconsejoDTO documentosrequisitoconsejo ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Documentosrequisitoconcejocohorte[");
		sb.append("id=").append(id);
		sb.append(separator).append("idDocrequisito=").append(idDocrequisito);
		sb.append(separator).append("idCohorte=").append(idCohorte);
		sb.append("]");
		return sb.toString();
	}
}
