/*
 * Created on 2026-05-24 ( 17:03:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDate;
import java.util.List;

/**
 * DTO class for "Documento"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DocumentoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY
    private Integer id ;
    //--- OTHER DATA FIELDS
    private String enlaceurl ;
    private LocalDate fechacargue ;
    private String keyfile ;
    private String observaciones ;
    private Integer idAdministrativo ;
    private Integer idAspirante ;
    private Integer idEstadodocumento ;
    private Integer idPlazo ;
    private Integer idDocumentosrequisitoconsejocohorte ;
    private Integer idDocumentosrequisitoprogramacohorte ;
    //--- LINKS ( RELATIONSHIPS )
    private List<CambiodocumentoDTO> cambiodocumentoList ;
    private List<CambiodocumentoDTO> cambiodocumentoList2 ;
    private AdministrativoDTO administrativo ;
    private AspiranteDTO aspirante ;
    private EstadodocumentoDTO estadodocumento ;
    private PlazoDTO plazo ;
    private DocumentosrequisitoconsejocohorteDTO documentosrequisitoconsejocohorte ;
    private DocumentosrequisitoprogramacohorteDTO documentosrequisitoprogramacohorte ;

    @Override
    public String toString() {
        String separator = "|";
        StringBuilder sb = new StringBuilder();
        sb.append("Documento[");
        sb.append("id=").append(id);
        sb.append(separator).append("fechacargue=").append(fechacargue);
        sb.append(separator).append("keyfile=").append(keyfile);
        sb.append(separator).append("idAdministrativo=").append(idAdministrativo);
        sb.append(separator).append("idAspirante=").append(idAspirante);
        sb.append(separator).append("idEstadodocumento=").append(idEstadodocumento);
        sb.append(separator).append("idPlazo=").append(idPlazo);
        sb.append(separator).append("idDocumentosrequisitoconsejocohorte=").append(idDocumentosrequisitoconsejocohorte);
        sb.append(separator).append("idDocumentosrequisitoprogramacohorte=").append(idDocumentosrequisitoprogramacohorte);
        sb.append("]");
        return sb.toString();
    }
}
