/*
 * Created on 2026-05-01 ( 13:45:55 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDate;

/**
 * DTO class for "Entrevista"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EntrevistaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private LocalDate fecha ;
    private float calificacion ;
    private int idTipoentrevista ;
    private int idEntrevistador ;
    private int idAspirante ;
    private int idEstado ;
    //--- LINKS ( RELATIONSHIPS )
    private TipoentrevistaDTO tipoentrevista ; 
    private EntrevistadorDTO entrevistador ; 
    private AspiranteDTO aspirante ; 
    private EstadoDTO estado ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Entrevista[");
		sb.append("id=").append(id);
		sb.append(separator).append("fecha=").append(fecha);
		sb.append(separator).append("calificacion=").append(calificacion);
		sb.append(separator).append("idTipoentrevista=").append(idTipoentrevista);
		sb.append(separator).append("idEntrevistador=").append(idEntrevistador);
		sb.append(separator).append("idAspirante=").append(idAspirante);
		sb.append(separator).append("idEstado=").append(idEstado);
		sb.append("]");
		return sb.toString();
	}
}
