/*
 * Created on 2026-05-14 ( 22:04:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * DTO class for "Pago"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PagoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private Integer idAspirante ;
    private Integer idEstado ;
    private Integer idPagoconcepto ;
    //--- LINKS ( RELATIONSHIPS )
    private AspiranteDTO aspirante ; 
    private EstadoDTO estado ; 
    private PagoconceptoDTO pagoconcepto ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Pago[");
		sb.append("id=").append(id);
		sb.append(separator).append("idAspirante=").append(idAspirante);
		sb.append(separator).append("idEstado=").append(idEstado);
		sb.append(separator).append("idPagoconcepto=").append(idPagoconcepto);
		sb.append("]");
		return sb.toString();
	}
}
