/*
 * Created on 2026-05-14 ( 22:38:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/**
 * DTO class for "Persona"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PersonaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String apellidos ;
    private String celular ;
    private String correo ;
    private boolean egresadoufps ;
    private String empresa ;
    private String experiencialaboral ;
    private LocalDate fechanacimiento ;
    private String nombres ;
    private BigDecimal promediopregrado ;
    private String telefono ;
    private String titulopregrado ;
    private String titulosposgrados ;
    private int idCapacidadexepcional ;
    private int idDiscapacidad ;
    private int idEstadocivil ;
    private int idGenero ;
    private int idGrupoetnico ;
    private int idPoblacionindigena ;
    private Integer idUbicacionnacimiento ;
    private Integer idUbicaciontrabajo ;
    private int idUbicacionvivienda ;
    //--- LINKS ( RELATIONSHIPS )
    private List<AdministrativoDTO> administrativoList ; 
    private List<AspiranteDTO> aspiranteList ; 
    private GeneroDTO genero ; 
    private UbicacionDTO ubicacionVivienda ;
    private UbicacionDTO ubicacionNacimiento ;
    private UbicacionDTO ubicacionTrabajo ;
    private GrupoetnicoDTO grupoetnico ; 
    private PoblacionindigenaDTO poblacionindigena ; 
    private DiscapacidadDTO discapacidad ; 
    private CapacidadexepcionalDTO capacidadexepcional ; 
    private EstadocivilDTO estadocivil ; 
    private List<UsuarioDTO> usuarioList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Persona[");
		sb.append("id=").append(id);
		sb.append(separator).append("apellidos=").append(apellidos);
		sb.append(separator).append("celular=").append(celular);
		sb.append(separator).append("correo=").append(correo);
		sb.append(separator).append("egresadoufps=").append(egresadoufps);
		sb.append(separator).append("empresa=").append(empresa);
		// attribute 'experiencialaboral' (type String) not usable in toString() 
		sb.append(separator).append("fechanacimiento=").append(fechanacimiento);
		sb.append(separator).append("nombres=").append(nombres);
		sb.append(separator).append("promediopregrado=").append(promediopregrado);
		sb.append(separator).append("telefono=").append(telefono);
		sb.append(separator).append("titulopregrado=").append(titulopregrado);
		// attribute 'titulosposgrados' (type String) not usable in toString() 
		sb.append(separator).append("idCapacidadexepcional=").append(idCapacidadexepcional);
		sb.append(separator).append("idDiscapacidad=").append(idDiscapacidad);
		sb.append(separator).append("idEstadocivil=").append(idEstadocivil);
		sb.append(separator).append("idGenero=").append(idGenero);
		sb.append(separator).append("idGrupoetnico=").append(idGrupoetnico);
		sb.append(separator).append("idPoblacionindigena=").append(idPoblacionindigena);
		sb.append(separator).append("idUbicacionnacimiento=").append(idUbicacionnacimiento);
		sb.append(separator).append("idUbicaciontrabajo=").append(idUbicaciontrabajo);
		sb.append(separator).append("idUbicacionvivienda=").append(idUbicacionvivienda);
		sb.append("]");
		return sb.toString();
	}
}
