/*
 * Created on 2026-05-18 ( 01:57:54 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalTime;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * DTO class for "Prueba"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PruebaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY
    private Integer id ;
    //--- OTHER DATA FIELDS
    private String nombre ;
    private String descripcion ;
    private LocalDate fecha;
    private LocalTime tiempo;
    private String motivocambio;
    private Integer idAspirante ;
    private Integer idCohorte ;
    private Integer idUbicacion ;
    private Integer idEstado;
    private Integer idTipoprueba;
    //--- LINKS ( RELATIONSHIPS )
    private AspiranteDTO aspirante ;
    private UbicacionDTO ubicacion ;
    private CohorteDTO cohorte ;
    private EstadoDTO estado;
    private TipopruebaDTO tipoprueba;

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Prueba[");
		sb.append("id=").append(id);
		sb.append(separator).append("nombre=").append(nombre);
		// attribute 'descripcion' (type String) not usable in toString() 
		sb.append(separator).append("idAspirante=").append(idAspirante);
		sb.append(separator).append("idCohorte=").append(idCohorte);
		sb.append(separator).append("idUbicacion=").append(idUbicacion);
		sb.append("]");
		return sb.toString();
	}
}
