/*
 * Created on 2026-05-14 ( 22:38:04 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDate;
import java.util.List;

/**
 * DTO class for "Semestre"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SemestreDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private LocalDate fechaFin ;
    private LocalDate fechaInicio ;
    private Integer idEstado ;
    private String nombre ;
    //--- LINKS ( RELATIONSHIPS )
    private List<CohorteDTO> cohorteList ; 
    private EstadoDTO estado ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Semestre[");
		sb.append("id=").append(id);
		sb.append(separator).append("fechaFin=").append(fechaFin);
		sb.append(separator).append("fechaInicio=").append(fechaInicio);
		sb.append(separator).append("idEstado=").append(idEstado);
		sb.append(separator).append("nombre=").append(nombre);
		sb.append("]");
		return sb.toString();
	}
}
