/*
 * Created on 2026-05-10 ( 01:19:12 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.util.List;

/**
 * DTO class for "Tipoentrevista"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TipoentrevistaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String descripcion ;
    private String tipo ;
    //--- LINKS ( RELATIONSHIPS )
    private List<EntrevistaDTO> entrevistaList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Tipoentrevista[");
		sb.append("id=").append(id);
		// attribute 'descripcion' (type String) not usable in toString() 
		sb.append(separator).append("tipo=").append(tipo);
		sb.append("]");
		return sb.toString();
	}
}
