/*
 * Created on 2026-05-14 ( 22:04:37 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.util.List;

/**
 * DTO class for "Ubicacion"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UbicacionDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String direccion ;
    private Boolean zonaurbana ;
    private Integer idMunicipio ;
    //--- LINKS ( RELATIONSHIPS )
    private List<DocumentopersonaDTO> documentopersonaList ; 
    private List<EntrevistaDTO> entrevistaList ; 
    private List<PersonaDTO> personaList ; 
    private List<PersonaDTO> personaList2 ; 
    private List<PersonaDTO> personaList3 ; 
    private List<PruebaDTO> pruebaList ; 
    private List<SedeDTO> sedeList ; 
    private MunicipioDTO municipio ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Ubicacion[");
		sb.append("id=").append(id);
		// attribute 'direccion' (type String) not usable in toString() 
		sb.append(separator).append("zonaurbana=").append(zonaurbana);
		sb.append(separator).append("idMunicipio=").append(idMunicipio);
		sb.append("]");
		return sb.toString();
	}
}
