/*
 * Created on 2026-05-01 ( 13:45:53 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDate;
import java.util.List;


/**
 * JPA entity class for "Administrativo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "administrativo")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AdministrativoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="id_persona", nullable=false)
    private int        idPersona ;

    @Column(name="fechainicio", nullable=false)
    private LocalDate  fechainicio ;

    @Column(name="fechasalida")
    private LocalDate  fechasalida ;

    @Column(name="id_estado", nullable=false)
    private int        idEstado ;

    @Column(name="id_cargo", nullable=false)
    private int        idCargo ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_persona", referencedColumnName="id", insertable=false, updatable=false)
    private PersonaEntity    persona ; 

    @ManyToOne
    @JoinColumn(name="id_estado", referencedColumnName="id", insertable=false, updatable=false)
    private EstadoEntity     estado ; 

    @ManyToOne
    @JoinColumn(name="id_cargo", referencedColumnName="id", insertable=false, updatable=false)
    private CargoEntity      cargo ; 

    @OneToMany(mappedBy="administrativo")
    private List<DocumentoEntity> documentoList ; 

    @OneToMany(mappedBy="administrativo")
    private List<EntrevistadorEntity> entrevistadorList ; 

    @OneToMany(mappedBy="administrativo")
    private List<EntrevistadoresEntity> entrevistadoresList ; 

    @OneToMany(mappedBy="administrativo")
    private List<FacultadEntity> facultadList ; 

    @OneToMany(mappedBy="administrativo")
    private List<ProgramaEntity> programaList ; 

}
