/*
 * Created on 2026-05-01 ( 13:45:53 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Aspirante"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "aspirante")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AspiranteEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="id_persona", nullable=false)
    private int        idPersona ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_persona", referencedColumnName="id", insertable=false, updatable=false)
    private PersonaEntity    persona ; 

    @OneToMany(mappedBy="aspirante")
    private List<DocumentoEntity> documentoList ; 

    @OneToMany(mappedBy="aspirante")
    private List<EntrevistaEntity> entrevistaList ; 

}
