/*
 * Created on 2026-05-14 ( 22:37:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.math.BigDecimal;
import java.util.List;


/**
 * JPA entity class for "Aspirante"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "aspirante")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AspiranteEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="puntuacion")
    private BigDecimal puntuacion ;

    @Column(name="id_cohorte", nullable=false)
    private int        idCohorte ;

    @Column(name="id_estado", nullable=false)
    private int        idEstado ;

    @Column(name="id_persona", nullable=false)
    private int        idPersona ;

    @Column(name="id_tipovinculacion", nullable=false)
    private int        idTipovinculacion ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_persona", referencedColumnName="id", insertable=false, updatable=false)
    private PersonaEntity    persona ; 

    @ManyToOne
    @JoinColumn(name="id_estado", referencedColumnName="id", insertable=false, updatable=false)
    private EstadoEntity     estado ; 

    @ManyToOne
    @JoinColumn(name="id_cohorte", referencedColumnName="id", insertable=false, updatable=false)
    private CohorteEntity    cohorte ; 

    @ManyToOne
    @JoinColumn(name="id_tipovinculacion", referencedColumnName="id", insertable=false, updatable=false)
    private TipovinculacionEntity tipovinculacion ; 

    @OneToMany(mappedBy="aspirante")
    private List<CalificacioncriterioEntity> calificacioncriterioList ; 

    @OneToMany(mappedBy="aspirante")
    private List<DocumentoEntity> documentoList ; 

    @OneToMany(mappedBy="aspirante")
    private List<EntrevistaEntity> entrevistaList ; 

    @OneToMany(mappedBy="aspirante")
    private List<ListaadmitidosEntity> listaadmitidosList ; 

    @OneToMany(mappedBy="aspirante")
    private List<PagoEntity> pagoList ; 

    @OneToMany(mappedBy="aspirante")
    private List<ResultadopruebaEntity> resultadopruebaList ; 

}
