/*
 * Created on 2026-05-13 ( 00:00:00 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.math.BigDecimal;


/**
 * JPA entity class for "Calificacioncriterio"
 *
 * @author Telosys
 *
 */
@Entity
@Table(
    name = "calificacioncriterio",
    uniqueConstraints = @UniqueConstraint(
        name = "calificacioncriterio_uq_aspirante_criterio",
        columnNames = {"id_aspirante", "id_criterio"}
    )
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CalificacioncriterioEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Integer id;

    //--- OTHER DATA FIELDS
    @Column(name = "id_aspirante", nullable = false)
    private Integer idAspirante;

    @Column(name = "id_criterio", nullable = false)
    private Integer idCriterio;

    @Column(name = "puntuacion", nullable = false, precision = 5, scale = 2)
    private BigDecimal puntuacion;

    @Column(name = "peso_snapshot", nullable = false, precision = 5, scale = 2)
    private BigDecimal pesoSnapshot;

    @Column(name = "observaciones", length = 65535)
    private String observaciones;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name = "id_aspirante", referencedColumnName = "id", insertable = false, updatable = false)
    private AspiranteEntity aspirante;

    @ManyToOne
    @JoinColumn(name = "id_criterio", referencedColumnName = "id", insertable = false, updatable = false)
    private CriterioaceptacionEntity criterioaceptacion;

}
