/*
 * Created on 2026-05-14 ( 22:37:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.math.BigDecimal;
import java.util.List;


/**
 * JPA entity class for "Criterioaceptacion"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "criterioaceptacion")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CriterioaceptacionEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="nombre", nullable=false, length=100)
    private String     nombre ;

    @Column(name="descripcion", length=65535)
    private String     descripcion ;

    @Column(name="peso", nullable=false)
    private BigDecimal peso ;

    @Column(name="id_cohorte", nullable=false)
    private int        idCohorte ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="criterioaceptacion")
    private List<CalificacioncriterioEntity> calificacioncriterioList ; 

    @ManyToOne
    @JoinColumn(name="id_cohorte", referencedColumnName="id", insertable=false, updatable=false)
    private CohorteEntity    cohorte ; 

}
