/*
 * Created on 2026-05-14 ( 22:04:33 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Discapacidad"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "discapacidad")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DiscapacidadEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="tipodiscapacidad", nullable=false, length=100)
    private String     tipodiscapacidad ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="discapacidad")
    private List<PersonaEntity> personaList ; 

}
