/*
 * Created on 2026-05-21 ( 15:00:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * JPA entity class for "Documentocohorte"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "documentocohorte")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DocumentocohorteEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="nombre", length=200)
    private String     nombre ;

    @Column(name="obligatorio")
    private Boolean    obligatorio ;

    @Column(name="id_cohorte", nullable=false)
    private Integer        idCohorte ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_cohorte", referencedColumnName="id", insertable=false, updatable=false)
    private CohorteEntity    cohorte ; 

}
