/*
 * Created on 2026-05-25 ( 18:46:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Documentosrequisitoconsejo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "documentosrequisitoconsejo")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DocumentosrequisitoconsejoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="nombre", length=200)
    private String     nombre ;

    @Column(name="tamanomaximo")
    private Integer    tamanomaximo ;

    @Column(name="urlformato", length=65535)
    private String     urlformato ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="documentosrequisitoconsejo")
    private List<DocumentosrequisitoconsejocohorteEntity> documentosrequisitoconsejocohorteList ; 

}
