/*
 * Created on 2026-05-24 ( 03:29:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * JPA entity class for "Documentosrequisitoconcejocohorte"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "documentosrequisitoconcejocohorte")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DocumentosrequisitoconcejocohorteEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="id_docrequisito")
    private Integer    idDocrequisito ;

    @Column(name="id_cohorte")
    private Integer    idCohorte ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_cohorte", referencedColumnName="id", insertable=false, updatable=false)
    private CohorteEntity    cohorte ; 

    @ManyToOne
    @JoinColumn(name="id_docrequisito", referencedColumnName="id", insertable=false, updatable=false)
    private DocumentosrequisitoconsejoEntity documentosrequisitoconsejo ; 

}
