/*
 * Created on 2026-05-14 ( 22:04:33 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * JPA entity class for "Documentopersona"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "documentopersona")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DocumentopersonaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="numerodocumento", nullable=false)
    private Integer        numerodocumento ;

    @Column(name="id_tipodocumento", nullable=false)
    private Integer        idTipodocumento ;

    @Column(name="id_lugarexpedicion", nullable=false)
    private Integer        idLugarexpedicion ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_tipodocumento", referencedColumnName="id", insertable=false, updatable=false)
    private TipodocumentoEntity tipodocumento ; 

    @ManyToOne
    @JoinColumn(name="id_lugarexpedicion", referencedColumnName="id", insertable=false, updatable=false)
    private UbicacionEntity  ubicacion ; 

}
