/*
 * Created on 2026-05-14 ( 22:37:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Estadocivil"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "estadocivil")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EstadocivilEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="estado", nullable=false, length=50)
    private String     estado ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="estadocivil")
    private List<PersonaEntity> personaList ; 

}
