/*
 * Created on 2026-05-10 ( 01:19:09 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Estado"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "estado")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EstadoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="entidad", nullable=false, length=50)
    private String     entidad ;

    @Column(name="tipo", nullable=false, length=50)
    private String     tipo ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="estado")
    private List<AdministrativoEntity> administrativoList ; 

    @OneToMany(mappedBy="estado")
    private List<AspiranteEntity> aspiranteList ; 

    @OneToMany(mappedBy="estado")
    private List<CohorteEntity> cohorteList ; 

    @OneToMany(mappedBy="estado")
    private List<EntrevistaEntity> entrevistaList ; 

    @OneToMany(mappedBy="estado")
    private List<PagoEntity> pagoList ; 

    @OneToMany(mappedBy="estado")
    private List<PagosEntity> pagosList ; 

    @OneToMany(mappedBy="estado")
    private List<SemestreEntity> semestreList ; 

}
