/*
 * Created on 2026-05-30 ( 21:33:03 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDate;


/**
 * JPA entity class for "Estudiantes"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "estudiantes")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EstudiantesEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="apellido", length=200)
    private String     apellido ;

    @Column(name="apellido2", length=200)
    private String     apellido2 ;

    @Column(name="cedula", length=200)
    private String     cedula ;

    @Column(name="codigo", length=200)
    private String     codigo ;

    @Column(name="email", length=200)
    private String     email ;

    @Column(name="esPosgrado")
    private Boolean    esposgrado ;

    @Column(name="fechalngreso")
    private LocalDate  fechalngreso ;

    @Column(name="fechaNacimiento")
    private LocalDate  fechanacimiento ;

    @Column(name="migrado", length=200)
    private String     migrado ;

    @Column(name="moodleld", length=200)
    private String     moodleld ;

    @Column(name="nombre", length=200)
    private String     nombre ;

    @Column(name="nombre2", length=200)
    private String     nombre2 ;

    @Column(name="telefono", length=200)
    private String     telefono ;

    @Column(name="cohorte_id")
    private Integer    cohorteId ;

    @Column(name="estado_estudiante_id")
    private Integer    estadoEstudianteId ;

    @Column(name="pensum_id")
    private Integer    pensumId ;

    @Column(name="programa_id")
    private Integer    programaId ;

    @Column(name="usuario_id")
    private Integer    usuarioId ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="programa_id", referencedColumnName="id", insertable=false, updatable=false)
    private ProgramaEntity  programa ; 

    @ManyToOne
    @JoinColumn(name="usuario_id", referencedColumnName="id", insertable=false, updatable=false)
    private UsuarioEntity   usuario ; 

}
