/*
 * Created on 2026-05-25 ( 18:46:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Grupoetnico"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "grupoetnico")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class GrupoetnicoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="grupo", nullable=false, length=100)
    private String     grupo ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="grupoetnico")
    private List<PersonaEntity> personaList ; 

}
