/*
 * Created on 2026-05-14 ( 22:38:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;


/**
 * JPA entity class for "Persona"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "persona")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PersonaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS
    @Column(name="apellidos", nullable=false, length=100)
    private String     apellidos ;

    @Column(name="celular", nullable=false, length=12)
    private String     celular ;

    @Column(name="correo", nullable=false, length=100)
    private String     correo ;

    @Column(name="egresadoufps", nullable=false)
    private Boolean    egresadoufps ;

    @Column(name="empresa", length=100)
    private String     empresa ;

    @Column(name="experiencialaboral", columnDefinition="TEXT")
    private String     experiencialaboral ;

    @Column(name="fechanacimiento", nullable=false)
    private LocalDate  fechanacimiento ;

    @Column(name="id_capacidadexepcional", nullable=false)
    private Integer    idCapacidadexepcional ;

    @Column(name="id_discapacidad", nullable=false)
    private Integer    idDiscapacidad ;

    @Column(name="id_estadocivil", nullable=false)
    private Integer    idEstadocivil ;

    @Column(name="id_genero", nullable=false)
    private Integer    idGenero ;

    @Column(name="id_grupoetnico", nullable=false)
    private Integer    idGrupoetnico ;

    @Column(name="id_poblacionindigena", nullable=false)
    private Integer    idPoblacionindigena ;

    @Column(name="id_ubicacionnacimiento")
    private Integer    idUbicacionnacimiento ;

    @Column(name="id_ubicaciontrabajo")
    private Integer    idUbicaciontrabajo ;

    @Column(name="id_ubicacionvivienda", nullable=false)
    private Integer    idUbicacionvivienda ;

    @Column(name="nombres", nullable=false, length=100)
    private String     nombres ;

    @Column(name="promediopregrado", precision=5, scale=2)
    private BigDecimal promediopregrado ;

    @Column(name="telefono", length=12)
    private String     telefono ;

    @Column(name="titulopregrado", nullable=false, length=100)
    private String     titulopregrado ;

    @Column(name="titulosposgrados", columnDefinition="TEXT")
    private String     titulosposgrados ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="persona")
    private List<AdministrativoEntity> administrativoList ;

    @OneToMany(mappedBy="persona")
    private List<AspiranteEntity> aspiranteList ;

    @ManyToOne
    @JoinColumn(name="id_genero", referencedColumnName="id", insertable=false, updatable=false)
    private GeneroEntity     genero ;

    @ManyToOne
    @JoinColumn(name="id_ubicacionnacimiento", referencedColumnName="id", insertable=false, updatable=false)
    private UbicacionEntity  ubicacionNacimiento ;

    @ManyToOne
    @JoinColumn(name="id_ubicaciontrabajo", referencedColumnName="id", insertable=false, updatable=false)
    private UbicacionEntity  ubicacionTrabajo ;

    @ManyToOne
    @JoinColumn(name="id_ubicacionvivienda", referencedColumnName="id", insertable=false, updatable=false)
    private UbicacionEntity  ubicacionVivienda ;

    @ManyToOne
    @JoinColumn(name="id_ubicacionvivienda", referencedColumnName="id", insertable=false, updatable=false)
    private UbicacionEntity  ubicacion2 ; 

    @ManyToOne
    @JoinColumn(name="id_ubicaciontrabajo", referencedColumnName="id", insertable=false, updatable=false)
    private UbicacionEntity  ubicacion3 ; 

    @ManyToOne
    @JoinColumn(name="id_grupoetnico", referencedColumnName="id", insertable=false, updatable=false)
    private GrupoetnicoEntity grupoetnico ; 

    @ManyToOne
    @JoinColumn(name="id_poblacionindigena", referencedColumnName="id", insertable=false, updatable=false)
    private PoblacionindigenaEntity poblacionindigena ; 

    @ManyToOne
    @JoinColumn(name="id_discapacidad", referencedColumnName="id", insertable=false, updatable=false)
    private DiscapacidadEntity discapacidad ; 

    @ManyToOne
    @JoinColumn(name="id_capacidadexepcional", referencedColumnName="id", insertable=false, updatable=false)
    private CapacidadexepcionalEntity capacidadexepcional ; 

    @ManyToOne
    @JoinColumn(name="id_estadocivil", referencedColumnName="id", insertable=false, updatable=false)
    private EstadocivilEntity estadocivil ; 

    @OneToMany(mappedBy="persona")
    private List<UsuarioEntity> usuarioList ;

}
