/*
 * Created on 2026-05-01 ( 13:45:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Programa"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "programa")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ProgramaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="codigo", nullable=false)
    private int        codigo ;

    @Column(name="nombre", nullable=false, length=100)
    private String     nombre ;

    @Column(name="duracion", nullable=false)
    private int        duracion ;

    @Column(name="correo", length=100)
    private String     correo ;

    @Column(name="registrosnies", length=20)
    private String     registrosnies ;

    @Column(name="nivelformacion", length=50)
    private String     nivelformacion ;

    @Column(name="titulo", length=100)
    private String     titulo ;

    @Column(name="rcmineducacion", length=65535)
    private String     rcmineducacion ;

    @Column(name="creditos")
    private Integer    creditos ;

    @Column(name="periodicidad", length=50)
    private String     periodicidad ;

    @Column(name="valormatricula")
    private Float      valormatricula ;

    @Column(name="id_sede", nullable=false)
    private int        idSede ;

    @Column(name="id_administrativo")
    private Integer    idAdministrativo ;

    @Column(name="id_facultad", nullable=false)
    private int        idFacultad ;

    @Column(name="id_otros")
    private int        idOtros ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="programa")
    private List<CargoEntity> cargoList ; 

    @OneToMany(mappedBy="programa")
    private List<OfertaacademicaEntity> ofertaacademicaList ; 

    @ManyToOne
    @JoinColumn(name="id_sede", referencedColumnName="id", insertable=false, updatable=false)
    private SedeEntity       sede ; 

    @ManyToOne
    @JoinColumn(name="id_administrativo", referencedColumnName="id", insertable=false, updatable=false)
    private AdministrativoEntity administrativo ; 

    @ManyToOne
    @JoinColumn(name="id_facultad", referencedColumnName="id", insertable=false, updatable=false)
    private FacultadEntity   facultad ; 

    @ManyToOne
    @JoinColumn(name="id_otros", referencedColumnName="id", insertable=false, updatable=false)
    private OtrosvaloresEntity otrosvalores ; 

}
