/*
 * Created on 2026-05-18 ( 01:57:54 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalTime;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Prueba"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "prueba")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PruebaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="nombre", nullable=false, length=100)
    private String     nombre ;

    @Column(name="descripcion", length=65535)
    private String     descripcion ;

    @Column(name="fecha")
    private LocalDate fecha;

    @Column(name="tiempo")
    private LocalTime tiempo;

    @Column(name="motivocambio", columnDefinition="TEXT")
    private String motivocambio;

    @Column(name="id_aspirante", nullable=false)
    private Integer        idAspirante ;

    @Column(name="id_cohorte", nullable=false)
    private Integer        idCohorte ;

    @Column(name="id_ubicacion", nullable=false)
    private Integer        idUbicacion ;

    @Column(name="id_estado")
    private Integer        idEstado;

    @Column(name="id_tipoprueba")
    private Integer        idTipoprueba;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_aspirante", referencedColumnName="id", insertable=false, updatable=false)
    private AspiranteEntity  aspirante ;

    @ManyToOne
    @JoinColumn(name="id_ubicacion", referencedColumnName="id", insertable=false, updatable=false)
    private UbicacionEntity  ubicacion ;

    @ManyToOne
    @JoinColumn(name="id_cohorte", referencedColumnName="id", insertable=false, updatable=false)
    private CohorteEntity    cohorte ;

    @ManyToOne
    @JoinColumn(name="id_estado", referencedColumnName="id", insertable=false, updatable=false)
    private EstadoEntity     estado;

    @ManyToOne
    @JoinColumn(name="id_tipoprueba", referencedColumnName="id", insertable=false, updatable=false)
    private TipopruebaEntity tipoprueba;

    @OneToMany(mappedBy="prueba")
    private List<ResultadopruebaEntity> resultadopruebaList ;

}
