/*
 * Created on 2026-05-14 ( 22:38:04 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.math.BigDecimal;


/**
 * JPA entity class for "Resultadoprueba"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "resultadoprueba")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ResultadopruebaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="calificacion")
    private BigDecimal calificacion ;

    @Column(name="id_aspirante", nullable=false)
    private int        idAspirante ;

    @Column(name="id_prueba", nullable=false)
    private int        idPrueba ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_aspirante", referencedColumnName="id", insertable=false, updatable=false)
    private AspiranteEntity  aspirante ; 

    @ManyToOne
    @JoinColumn(name="id_prueba", referencedColumnName="id", insertable=false, updatable=false)
    private PruebaEntity     prueba ; 

}
