/*
 * Created on 2026-05-14 ( 22:38:05 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Tipoentrevista"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tipoentrevista")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TipoentrevistaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="descripcion", length=65535)
    private String     descripcion ;

    @Column(name="tipo", nullable=false, length=100)
    private String     tipo ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="tipoentrevista")
    private List<EntrevistaEntity> entrevistaList ; 

}
