/*
 * Created on 2026-05-10 ( 01:19:12 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Tipoplazo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tipoplazo")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TipoplazoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="descripcion", length=65535)
    private String     descripcion ;

    @Column(name="tipo", nullable=false, length=100)
    private String     tipo ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="tipoplazo")
    private List<PlazoEntity> plazoList ; 

}
