/*
 * Created on 2026-05-10 ( 01:19:12 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * JPA entity class for "Usuario"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "usuario")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UsuarioEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="id_clave", nullable=false)
    private Integer        idClave ;

    @Column(name="id_persona", nullable=false)
    private Integer        idPersona ;

    @Column(name="id_rol", nullable=false)
    private Integer        idRol ;

    @Column(name="nombreusuario", nullable=false, length=50)
    private String     nombreusuario ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_clave", referencedColumnName="id", insertable=false, updatable=false)
    private ClaveEntity      clave ; 

    @ManyToOne
    @JoinColumn(name="id_persona", referencedColumnName="id", insertable=false, updatable=false)
    private PersonaEntity    persona ; 

    @ManyToOne
    @JoinColumn(name="id_rol", referencedColumnName="id", insertable=false, updatable=false)
    private RolEntity        rol ; 

}
