/*
 * Created on 2026-04-30 ( 18:48:50 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.EntrevistadoresEntity;
import ufps.edu.co.persistence.repositories.EntrevistadoresRepository;
import ufps.edu.co.rest.dto.EntrevistadoresDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Entrevistadores" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class EntrevistadoresService extends GenericService<EntrevistadoresEntity, EntrevistadoresDTO> {

    @Autowired
    private EntrevistadoresRepository repository;

    public EntrevistadoresService() {
        super(EntrevistadoresEntity.class, EntrevistadoresDTO.class);
    }

    @Transactional(readOnly = true)
    public List<EntrevistadoresDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public EntrevistadoresDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public EntrevistadoresDTO create(EntrevistadoresDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public EntrevistadoresDTO update(Integer id, EntrevistadoresDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevistadores no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevistadores no encontrado con id: " + id));
        repository.deleteById(id);
    }
}