/*
 * Created on 2026-04-24 ( 22:23:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.controllers;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import ufps.edu.co.rest.dto.ProgramaPosgradoDTO;
import ufps.edu.co.services.ProgramaPosgradoService;

@RestController
@RequestMapping(value = "/api/v1/programaposgrado", produces = MediaType.APPLICATION_JSON_VALUE)
public class ProgramaPosgradoRestController {

    @Autowired
    private ProgramaPosgradoService service;

    /**
     * Get ALL
     *
     * @return 200 con lista de DTO
     */
    @GetMapping("")
    public ResponseEntity<List<ProgramaPosgradoDTO>> findAll() {
        List<ProgramaPosgradoDTO> list = service.findAll();
        return ResponseEntity.ok(list); // 200 OK
    }

    /**
     * Get ONE identified by the given PK
     *
     * @param id
     * @return 200 con DTO o 404 si no existe
     */
    @GetMapping("/{id}")
    public ResponseEntity<ProgramaPosgradoDTO> findById(@PathVariable int id) {
        ProgramaPosgradoDTO programaPosgradoDTO = service.findById(id);
        if ( programaPosgradoDTO != null ) {
            return ResponseEntity.ok(programaPosgradoDTO); // 200 OK
        } else {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }

    /**
     * Create
     *
     * @param programaPosgradoDTO
     * @return 201 creado o 409 si ya existe
     */
    @PostMapping("")
    public ResponseEntity<ProgramaPosgradoDTO> create(@RequestBody ProgramaPosgradoDTO programaPosgradoDTO) {
        ProgramaPosgradoDTO created = service.create(programaPosgradoDTO);
        return ResponseEntity.status(HttpStatus.CREATED).body(created); // 201 Created
    }

    /**
     * Update if exists
     *
     * @param id
     * @param programaPosgradoDTO
     * @return 200 con DTO actualizado o 404 si no existe
     */
    @PutMapping("/{id}")
    public ResponseEntity<ProgramaPosgradoDTO> update(@PathVariable int id, @RequestBody ProgramaPosgradoDTO programaPosgradoDTO) {
        try {
            ProgramaPosgradoDTO updated = service.update(id, programaPosgradoDTO);
            return ResponseEntity.ok(updated); // 200 OK
        } catch (RuntimeException e) {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }

    /**
     * Delete by PK
     *
     * @param id
     * @return 204 eliminado o 404 si no existe
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteById(@PathVariable int id) {
        try {
            service.deleteById(id);
            return ResponseEntity.noContent().build(); // 204 No content
        } catch (RuntimeException e) {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }
}
