/*
 * Created on 2026-04-24 ( 22:23:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.controllers;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import ufps.edu.co.rest.dto.TipoDocumentoDTO;
import ufps.edu.co.services.TipoDocumentoService;

@RestController
@RequestMapping(value = "/api/v1/tipodocumento", produces = MediaType.APPLICATION_JSON_VALUE)
public class TipoDocumentoRestController {

    @Autowired
    private TipoDocumentoService service;

    /**
     * Get ALL
     *
     * @return 200 con lista de DTO
     */
    @GetMapping("")
    public ResponseEntity<List<TipoDocumentoDTO>> findAll() {
        List<TipoDocumentoDTO> list = service.findAll();
        return ResponseEntity.ok(list); // 200 OK
    }

    /**
     * Get ONE identified by the given PK
     *
     * @param id
     * @return 200 con DTO o 404 si no existe
     */
    @GetMapping("/{id}")
    public ResponseEntity<TipoDocumentoDTO> findById(@PathVariable int id) {
        TipoDocumentoDTO tipoDocumentoDTO = service.findById(id);
        if ( tipoDocumentoDTO != null ) {
            return ResponseEntity.ok(tipoDocumentoDTO); // 200 OK
        } else {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }

    /**
     * Create
     *
     * @param tipoDocumentoDTO
     * @return 201 creado o 409 si ya existe
     */
    @PostMapping("")
    public ResponseEntity<TipoDocumentoDTO> create(@RequestBody TipoDocumentoDTO tipoDocumentoDTO) {
        TipoDocumentoDTO created = service.create(tipoDocumentoDTO);
        return ResponseEntity.status(HttpStatus.CREATED).body(created); // 201 Created
    }

    /**
     * Update if exists
     *
     * @param id
     * @param tipoDocumentoDTO
     * @return 200 con DTO actualizado o 404 si no existe
     */
    @PutMapping("/{id}")
    public ResponseEntity<TipoDocumentoDTO> update(@PathVariable int id, @RequestBody TipoDocumentoDTO tipoDocumentoDTO) {
        try {
            TipoDocumentoDTO updated = service.update(id, tipoDocumentoDTO);
            return ResponseEntity.ok(updated); // 200 OK
        } catch (RuntimeException e) {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }

    /**
     * Delete by PK
     *
     * @param id
     * @return 204 eliminado o 404 si no existe
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteById(@PathVariable int id) {
        try {
            service.deleteById(id);
            return ResponseEntity.noContent().build(); // 204 No content
        } catch (RuntimeException e) {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }
}
