/*
 * Created on 2026-04-24 ( 22:23:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.controllers;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import ufps.edu.co.rest.dto.UsuarioAspiranteDTO;
import ufps.edu.co.services.UsuarioAspiranteService;

@RestController
@RequestMapping(value = "/api/v1/usuarioaspirante", produces = MediaType.APPLICATION_JSON_VALUE)
public class UsuarioAspiranteRestController {

    @Autowired
    private UsuarioAspiranteService service;

    /**
     * Get ALL
     *
     * @return 200 con lista de DTO
     */
    @GetMapping("")
    public ResponseEntity<List<UsuarioAspiranteDTO>> findAll() {
        List<UsuarioAspiranteDTO> list = service.findAll();
        return ResponseEntity.ok(list); // 200 OK
    }

    /**
     * Get ONE identified by the given PK
     *
     * @param idUsuario
     * @return 200 con DTO o 404 si no existe
     */
    @GetMapping("/{idUsuario}")
    public ResponseEntity<UsuarioAspiranteDTO> findById(@PathVariable int idUsuario) {
        UsuarioAspiranteDTO usuarioAspiranteDTO = service.findById(idUsuario);
        if ( usuarioAspiranteDTO != null ) {
            return ResponseEntity.ok(usuarioAspiranteDTO); // 200 OK
        } else {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }

    /**
     * Create
     *
     * @param usuarioAspiranteDTO
     * @return 201 creado o 409 si ya existe
     */
    @PostMapping("")
    public ResponseEntity<UsuarioAspiranteDTO> create(@RequestBody UsuarioAspiranteDTO usuarioAspiranteDTO) {
        try {
            UsuarioAspiranteDTO created = service.create(usuarioAspiranteDTO);
            return ResponseEntity.status(HttpStatus.CREATED).body(created); // 201 Created
        } catch (RuntimeException e) {
            return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
        }
    }

    /**
     * Update if exists
     *
     * @param idUsuario
     * @param usuarioAspiranteDTO
     * @return 200 con DTO actualizado o 404 si no existe
     */
    @PutMapping("/{idUsuario}")
    public ResponseEntity<UsuarioAspiranteDTO> update(@PathVariable int idUsuario, @RequestBody UsuarioAspiranteDTO usuarioAspiranteDTO) {
        try {
            UsuarioAspiranteDTO updated = service.update(idUsuario, usuarioAspiranteDTO);
            return ResponseEntity.ok(updated); // 200 OK
        } catch (RuntimeException e) {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }

    /**
     * Delete by PK
     *
     * @param idUsuario
     * @return 204 eliminado o 404 si no existe
     */
    @DeleteMapping("/{idUsuario}")
    public ResponseEntity<Void> deleteById(@PathVariable int idUsuario) {
        try {
            service.deleteById(idUsuario);
            return ResponseEntity.noContent().build(); // 204 No content
        } catch (RuntimeException e) {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }
}
