/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DocumentoRequeridoOfertaEntity;
import ufps.edu.co.persistence.repositories.DocumentoRequeridoOfertaRepository;
import ufps.edu.co.rest.dto.DocumentoRequeridoOfertaDTO;
import ufps.edu.co.services.commons.GenericService;

/**
 * REST service for entity "DocumentoRequeridoOferta" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DocumentoRequeridoOfertaService extends GenericService<DocumentoRequeridoOfertaEntity, DocumentoRequeridoOfertaDTO> {

    @Autowired
    private DocumentoRequeridoOfertaRepository repository;

    public DocumentoRequeridoOfertaService() {
        super(DocumentoRequeridoOfertaEntity.class, DocumentoRequeridoOfertaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<DocumentoRequeridoOfertaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public DocumentoRequeridoOfertaDTO findById(int id) {
        return entityToDto(repository.findById(id));
    }

    public DocumentoRequeridoOfertaDTO create(DocumentoRequeridoOfertaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public DocumentoRequeridoOfertaDTO update(int id, DocumentoRequeridoOfertaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("DocumentoRequeridoOferta no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(int id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("DocumentoRequeridoOferta no encontrado con id: " + id));
        repository.deleteById(id);
    }
}