/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.EstadoDocumentoEntity;
import ufps.edu.co.persistence.repositories.EstadoDocumentoRepository;
import ufps.edu.co.rest.dto.EstadoDocumentoDTO;
import ufps.edu.co.services.commons.GenericService;

/**
 * REST service for entity "EstadoDocumento" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class EstadoDocumentoService extends GenericService<EstadoDocumentoEntity, EstadoDocumentoDTO> {

    @Autowired
    private EstadoDocumentoRepository repository;

    public EstadoDocumentoService() {
        super(EstadoDocumentoEntity.class, EstadoDocumentoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<EstadoDocumentoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public EstadoDocumentoDTO findById(int id) {
        return entityToDto(repository.findById(id));
    }

    public EstadoDocumentoDTO create(EstadoDocumentoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public EstadoDocumentoDTO update(int id, EstadoDocumentoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("EstadoDocumento no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(int id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("EstadoDocumento no encontrado con id: " + id));
        repository.deleteById(id);
    }
}