/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.EtapaCompletadaEntity;
import ufps.edu.co.persistence.repositories.EtapaCompletadaRepository;
import ufps.edu.co.rest.dto.EtapaCompletadaDTO;
import ufps.edu.co.services.commons.GenericService;

/**
 * REST service for entity "EtapaCompletada" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class EtapaCompletadaService extends GenericService<EtapaCompletadaEntity, EtapaCompletadaDTO> {

    @Autowired
    private EtapaCompletadaRepository repository;

    public EtapaCompletadaService() {
        super(EtapaCompletadaEntity.class, EtapaCompletadaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<EtapaCompletadaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public EtapaCompletadaDTO findById(int id) {
        return entityToDto(repository.findById(id));
    }

    public EtapaCompletadaDTO create(EtapaCompletadaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public EtapaCompletadaDTO update(int id, EtapaCompletadaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("EtapaCompletada no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(int id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("EtapaCompletada no encontrado con id: " + id));
        repository.deleteById(id);
    }
}