/*
 * Created on 2026-04-24 ( 22:23:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.HistorialEstadoDocumentoEntity;
import ufps.edu.co.persistence.repositories.HistorialEstadoDocumentoRepository;
import ufps.edu.co.rest.dto.HistorialEstadoDocumentoDTO;
import ufps.edu.co.services.commons.GenericService;

/**
 * REST service for entity "HistorialEstadoDocumento" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class HistorialEstadoDocumentoService extends GenericService<HistorialEstadoDocumentoEntity, HistorialEstadoDocumentoDTO> {

    @Autowired
    private HistorialEstadoDocumentoRepository repository;

    public HistorialEstadoDocumentoService() {
        super(HistorialEstadoDocumentoEntity.class, HistorialEstadoDocumentoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<HistorialEstadoDocumentoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public HistorialEstadoDocumentoDTO findById(int id) {
        return entityToDto(repository.findById(id));
    }

    public HistorialEstadoDocumentoDTO create(HistorialEstadoDocumentoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public HistorialEstadoDocumentoDTO update(int id, HistorialEstadoDocumentoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("HistorialEstadoDocumento no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(int id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("HistorialEstadoDocumento no encontrado con id: " + id));
        repository.deleteById(id);
    }
}