/*
 * Created on 2026-04-24 ( 22:23:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.PersonalAdministrativoEntity;
import ufps.edu.co.persistence.repositories.PersonalAdministrativoRepository;
import ufps.edu.co.rest.dto.PersonalAdministrativoDTO;
import ufps.edu.co.services.commons.GenericService;

/**
 * REST service for entity "PersonalAdministrativo" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class PersonalAdministrativoService extends GenericService<PersonalAdministrativoEntity, PersonalAdministrativoDTO> {

    @Autowired
    private PersonalAdministrativoRepository repository;

    public PersonalAdministrativoService() {
        super(PersonalAdministrativoEntity.class, PersonalAdministrativoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<PersonalAdministrativoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public PersonalAdministrativoDTO findById(int id) {
        return entityToDto(repository.findById(id));
    }

    public PersonalAdministrativoDTO create(PersonalAdministrativoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public PersonalAdministrativoDTO update(int id, PersonalAdministrativoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("PersonalAdministrativo no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(int id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("PersonalAdministrativo no encontrado con id: " + id));
        repository.deleteById(id);
    }
}