/*
 * Created on 2026-04-24 ( 22:23:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.ProgramaPosgradoEntity;
import ufps.edu.co.persistence.repositories.ProgramaPosgradoRepository;
import ufps.edu.co.rest.dto.ProgramaPosgradoDTO;
import ufps.edu.co.services.commons.GenericService;

/**
 * REST service for entity "ProgramaPosgrado" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class ProgramaPosgradoService extends GenericService<ProgramaPosgradoEntity, ProgramaPosgradoDTO> {

    @Autowired
    private ProgramaPosgradoRepository repository;

    public ProgramaPosgradoService() {
        super(ProgramaPosgradoEntity.class, ProgramaPosgradoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<ProgramaPosgradoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public ProgramaPosgradoDTO findById(int id) {
        return entityToDto(repository.findById(id));
    }

    public ProgramaPosgradoDTO create(ProgramaPosgradoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public ProgramaPosgradoDTO update(int id, ProgramaPosgradoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("ProgramaPosgrado no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(int id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("ProgramaPosgrado no encontrado con id: " + id));
        repository.deleteById(id);
    }
}