/*
 * Created on 2026-04-24 ( 22:23:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.ResidenciaEntity;
import ufps.edu.co.persistence.repositories.ResidenciaRepository;
import ufps.edu.co.rest.dto.ResidenciaDTO;
import ufps.edu.co.services.commons.GenericService;

/**
 * REST service for entity "Residencia" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class ResidenciaService extends GenericService<ResidenciaEntity, ResidenciaDTO> {

    @Autowired
    private ResidenciaRepository repository;

    public ResidenciaService() {
        super(ResidenciaEntity.class, ResidenciaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<ResidenciaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public ResidenciaDTO findById(int id) {
        return entityToDto(repository.findById(id));
    }

    public ResidenciaDTO create(ResidenciaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public ResidenciaDTO update(int id, ResidenciaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Residencia no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(int id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Residencia no encontrado con id: " + id));
        repository.deleteById(id);
    }
}