/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.CambioDocumentoEntity;
import ufps.edu.co.persistence.repositories.CambioDocumentoRepository;
import ufps.edu.co.rest.dto.CambioDocumentoDTO;
import ufps.edu.co.services.commons.GenericService;

/**
 * REST service for entity "CambioDocumento" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class CambioDocumentoService extends GenericService<CambioDocumentoEntity, CambioDocumentoDTO> {

    @Autowired
    private CambioDocumentoRepository repository;

    public CambioDocumentoService() {
        super(CambioDocumentoEntity.class, CambioDocumentoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<CambioDocumentoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public CambioDocumentoDTO findById(int id) {
        return entityToDto(repository.findById(id));
    }

    public CambioDocumentoDTO create(CambioDocumentoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public CambioDocumentoDTO update(int id, CambioDocumentoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("CambioDocumento no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(int id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("CambioDocumento no encontrado con id: " + id));
        repository.deleteById(id);
    }
}