/*
 * Created on 2026-04-24 ( 22:23:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.OfertaAcademicaEntity;
import ufps.edu.co.persistence.repositories.OfertaAcademicaRepository;
import ufps.edu.co.rest.dto.OfertaAcademicaDTO;
import ufps.edu.co.services.commons.GenericService;

/**
 * REST service for entity "OfertaAcademica" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class OfertaAcademicaService extends GenericService<OfertaAcademicaEntity, OfertaAcademicaDTO> {

    @Autowired
    private OfertaAcademicaRepository repository;

    public OfertaAcademicaService() {
        super(OfertaAcademicaEntity.class, OfertaAcademicaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<OfertaAcademicaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public OfertaAcademicaDTO findById(int id) {
        return entityToDto(repository.findById(id));
    }

    public OfertaAcademicaDTO create(OfertaAcademicaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public OfertaAcademicaDTO update(int id, OfertaAcademicaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("OfertaAcademica no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(int id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("OfertaAcademica no encontrado con id: " + id));
        repository.deleteById(id);
    }
}