/*
 * Created on 2026-04-24 ( 22:23:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.TipoEtapaEntity;
import ufps.edu.co.persistence.repositories.TipoEtapaRepository;
import ufps.edu.co.rest.dto.TipoEtapaDTO;
import ufps.edu.co.services.commons.GenericService;

/**
 * REST service for entity "TipoEtapa" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class TipoEtapaService extends GenericService<TipoEtapaEntity, TipoEtapaDTO> {

    @Autowired
    private TipoEtapaRepository repository;

    public TipoEtapaService() {
        super(TipoEtapaEntity.class, TipoEtapaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<TipoEtapaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public TipoEtapaDTO findById(int id) {
        return entityToDto(repository.findById(id));
    }

    public TipoEtapaDTO create(TipoEtapaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public TipoEtapaDTO update(int id, TipoEtapaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("TipoEtapa no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(int id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("TipoEtapa no encontrado con id: " + id));
        repository.deleteById(id);
    }
}