/*
 * Created on 2026-04-24 ( 22:23:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.TipoDocumentoEntity;
import ufps.edu.co.persistence.repositories.TipoDocumentoRepository;
import ufps.edu.co.rest.dto.TipoDocumentoDTO;
import ufps.edu.co.services.commons.GenericService;

/**
 * REST service for entity "TipoDocumento" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class TipoDocumentoService extends GenericService<TipoDocumentoEntity, TipoDocumentoDTO> {

    @Autowired
    private TipoDocumentoRepository repository;

    public TipoDocumentoService() {
        super(TipoDocumentoEntity.class, TipoDocumentoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<TipoDocumentoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public TipoDocumentoDTO findById(int id) {
        return entityToDto(repository.findById(id));
    }

    public TipoDocumentoDTO create(TipoDocumentoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public TipoDocumentoDTO update(int id, TipoDocumentoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("TipoDocumento no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(int id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("TipoDocumento no encontrado con id: " + id));
        repository.deleteById(id);
    }
}