# ENVIROMENT VARIABLES
spring.config.import=optional:file:.env.properties

# Server configuration
server.port=8090
spring.application.name=Posgrados API
server.forward-headers-strategy=framework

# API documentation settings
springdoc.api-docs.enabled=${ENABLE_API_DOCS}
springdoc.swagger-ui.enabled=${ENABLE_SWAGGER_UI}
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/dev/docs/swagger-ui.html

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}

# Security settings
# # spring.security.user.name=${SPRING_SECURITY_USER}
# # spring.security.user.password=${SPRING_SECURITY_PASSWORD}

# logging config
# # # logging.level.root=INFO
# # # logging.level.ufps.edu.co=DEBUG
# # # logging.level.ufps.edu.co.persistence=DEBUG
# # # logging.level.ufps.edu.co.rest.controllers=DEBUG
# # # logging.level.ufps.edu.co.rest.services=DEBUG
