/*
 * Created on 2026-05-24 ( 03:29:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.controllers.rest;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import ufps.edu.co.rest.dto.DocumentosrequisitoconcejocohorteDTO;
import ufps.edu.co.rest.services.DocumentosrequisitoconcejocohorteService;

@RestController
@RequestMapping(value = "/api/v1/documentosrequisitoconcejocohorte", produces = MediaType.APPLICATION_JSON_VALUE)
public class DocumentosrequisitoconcejocohorteRestController {

    @Autowired
    private DocumentosrequisitoconcejocohorteService service;

    /**
     * Get ALL
     *
     * @return 200 con lista de DTO
     */
    @GetMapping("")
    public ResponseEntity<List<DocumentosrequisitoconcejocohorteDTO>> findAll() {
        List<DocumentosrequisitoconcejocohorteDTO> list = service.findAll();
        return ResponseEntity.ok(list); // 200 OK
    }

    /**
     * Get ONE identified by the given PK
     *
     * @param id
     * @return 200 con DTO o 404 si no existe
     */
    @GetMapping("/{id}")
    public ResponseEntity<DocumentosrequisitoconcejocohorteDTO> findById(@PathVariable Integer id) {
        DocumentosrequisitoconcejocohorteDTO documentosrequisitoconcejocohorteDTO = service.findById(id);
        if ( documentosrequisitoconcejocohorteDTO != null ) {
            return ResponseEntity.ok(documentosrequisitoconcejocohorteDTO); // 200 OK
        } else {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }

    /**
     * Create
     *
     * @param documentosrequisitoconcejocohorteDTO
     * @return 201 creado o 409 si ya existe
     */
    @PostMapping("")
    public ResponseEntity<DocumentosrequisitoconcejocohorteDTO> create(@RequestBody DocumentosrequisitoconcejocohorteDTO documentosrequisitoconcejocohorteDTO) {
        DocumentosrequisitoconcejocohorteDTO created = service.create(documentosrequisitoconcejocohorteDTO);
        return ResponseEntity.status(HttpStatus.CREATED).body(created); // 201 Created
    }

    /**
     * Update if exists
     *
     * @param id
     * @param documentosrequisitoconcejocohorteDTO
     * @return 200 con DTO actualizado o 404 si no existe
     */
    @PutMapping("/{id}")
    public ResponseEntity<DocumentosrequisitoconcejocohorteDTO> update(@PathVariable Integer id, @RequestBody DocumentosrequisitoconcejocohorteDTO documentosrequisitoconcejocohorteDTO) {
        try {
            DocumentosrequisitoconcejocohorteDTO updated = service.update(id, documentosrequisitoconcejocohorteDTO);
            return ResponseEntity.ok(updated); // 200 OK
        } catch (RuntimeException e) {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }

    /**
     * Delete by PK
     *
     * @param id
     * @return 204 eliminado o 404 si no existe
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteById(@PathVariable Integer id) {
        try {
            service.deleteById(id);
            return ResponseEntity.noContent().build(); // 204 No content
        } catch (RuntimeException e) {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }
}