/*
 * Created on 2026-05-18 ( 01:57:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.AdmitidoEntity;
import ufps.edu.co.persistence.repositories.AdmitidoRepository;
import ufps.edu.co.rest.dto.AdmitidoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Admitido" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class AdmitidoService extends GenericService<AdmitidoEntity, AdmitidoDTO> {

    @Autowired
    private AdmitidoRepository repository;

    public AdmitidoService() {
        super(AdmitidoEntity.class, AdmitidoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<AdmitidoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public AdmitidoDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public AdmitidoDTO create(AdmitidoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public AdmitidoDTO update(Integer id, AdmitidoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Admitido no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Admitido no encontrado con id: " + id));
        repository.deleteById(id);
    }
}