/*
 * Created on 2026-05-18 ( 01:57:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.AspiranteEntity;
import ufps.edu.co.persistence.repositories.AspiranteRepository;
import ufps.edu.co.rest.dto.AspiranteDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Aspirante" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class AspiranteService extends GenericService<AspiranteEntity, AspiranteDTO> {

    @Autowired
    private AspiranteRepository repository;

    public AspiranteService() {
        super(AspiranteEntity.class, AspiranteDTO.class);
    }

    @Transactional(readOnly = true)
    public List<AspiranteDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public AspiranteDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public AspiranteDTO create(AspiranteDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public AspiranteDTO update(Integer id, AspiranteDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Aspirante no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Aspirante no encontrado con id: " + id));
        repository.deleteById(id);
    }

    @Transactional(readOnly = true)
    public List<AspiranteDTO> findWithDocuments() {
        return entityListToDtoList(repository.findValidados());
    }

    @Transactional(readOnly = true)
    public List<AspiranteDTO> findCalificados() {
        return entityListToDtoList(repository.findCalificados());
    }

    @Transactional(readOnly = true)
    public List<AspiranteDTO> findPorCalificar() {
        return entityListToDtoList(repository.findPorCalificar());
    }

    @Transactional(readOnly = true)
    public List<AspiranteDTO> findByCohorte(int idCohorte) {
        return entityListToDtoList(repository.findByIdCohorte(idCohorte));
    }

    public long countValidados() {
        return repository.countByEstadoTipoIn(
                List.of("VALIDADO_POR_CALIFICAR", "VALIDADO_EN_PROGRESO", "VALIDADO_CALIFICADO"));
    }

    public long countPorCalificar() {
        return repository.countByEstadoTipoIn(
                List.of("VALIDADO_POR_CALIFICAR", "VALIDADO_EN_PROGRESO"));
    }

    public long countCalificados() {
        return repository.countByEstadoTipoIn(List.of("VALIDADO_CALIFICADO"));
    }

    public AspiranteDTO updateEstado(Integer idAspirante, Integer idEstado) {
        AspiranteEntity entity = repository.findById(idAspirante)
                .orElseThrow(() -> new RuntimeException("Aspirante no encontrado con id: " + idAspirante));
        entity.setIdEstado(idEstado);
        return entityToDto(repository.save(entity));
    }
}