/*
 * Created on 2026-05-14 ( 22:04:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.CalificacioncriterioEntity;
import ufps.edu.co.persistence.repositories.CalificacioncriterioRepository;
import ufps.edu.co.rest.dto.CalificacioncriterioDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Calificacioncriterio" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class CalificacioncriterioService extends GenericService<CalificacioncriterioEntity, CalificacioncriterioDTO> {

    @Autowired
    private CalificacioncriterioRepository repository;

    public CalificacioncriterioService() {
        super(CalificacioncriterioEntity.class, CalificacioncriterioDTO.class);
    }

    @Transactional(readOnly = true)
    public List<CalificacioncriterioDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public CalificacioncriterioDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public CalificacioncriterioDTO create(CalificacioncriterioDTO dto) {
        if (repository.existsById(dto.getId())) {
            throw new RuntimeException("Calificacioncriterio ya existe con id: " + dto.getId());
        }
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public CalificacioncriterioDTO update(Integer id, CalificacioncriterioDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Calificacioncriterio no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Calificacioncriterio no encontrado con id: " + id));
        repository.deleteById(id);
    }
}