/*
 * Created on 2026-05-18 ( 01:57:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import java.util.Optional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.CalificacioncriterioEntity;
import ufps.edu.co.persistence.repositories.CalificacioncriterioRepository;
import ufps.edu.co.rest.dto.CalificacioncriterioDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Calificacioncriterio" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class CalificacioncriterioService extends GenericService<CalificacioncriterioEntity, CalificacioncriterioDTO> {

    @Autowired
    private CalificacioncriterioRepository repository;

    public CalificacioncriterioService() {
        super(CalificacioncriterioEntity.class, CalificacioncriterioDTO.class);
    }

    @Transactional(readOnly = true)
    public List<CalificacioncriterioDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public CalificacioncriterioDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public List<CalificacioncriterioDTO> findByIdAspirante(Integer idAspirante) {
        return entityListToDtoList(repository.findByIdAspirante(idAspirante));
    }

    public CalificacioncriterioDTO findByIdCriterio(Integer idAspirante, Integer idCriterio) {
        return entityToDto(repository.findByIdAspiranteAndIdCriterio(idAspirante, idCriterio));
    }

    public List<CalificacioncriterioDTO> findByIdCriterio(Integer idCriterio) {
        return entityListToDtoList(repository.findByIdCriterio(idCriterio));
    }


    public Boolean existsByAspiranteAndCriterio(Integer idAspirante, Integer idCriterio) {
        return repository.existsByIdAspiranteAndIdCriterio(idAspirante, idCriterio);
    }

    @Transactional(readOnly = true)
    public Optional<CalificacioncriterioDTO> findByIdAspiranteAndIdCriterio(Integer idAspirante, Integer idCriterio) {
        return repository.findByIdAspiranteAndIdCriterio(idAspirante, idCriterio)
                .map(entity -> entityToDto(entity));
    }

    public CalificacioncriterioDTO create(CalificacioncriterioDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public CalificacioncriterioDTO update(Integer id, CalificacioncriterioDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Calificacioncriterio no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Calificacioncriterio no encontrado con id: " + id));
        repository.deleteById(id);
    }
}