/*
 * Created on 2026-05-14 ( 22:04:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.CapacidadexepcionalEntity;
import ufps.edu.co.persistence.repositories.CapacidadexepcionalRepository;
import ufps.edu.co.rest.dto.CapacidadexepcionalDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Capacidadexepcional" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class CapacidadexepcionalService extends GenericService<CapacidadexepcionalEntity, CapacidadexepcionalDTO> {

    @Autowired
    private CapacidadexepcionalRepository repository;

    public CapacidadexepcionalService() {
        super(CapacidadexepcionalEntity.class, CapacidadexepcionalDTO.class);
    }

    @Transactional(readOnly = true)
    public List<CapacidadexepcionalDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public CapacidadexepcionalDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public CapacidadexepcionalDTO create(CapacidadexepcionalDTO dto) {
        if (repository.existsById(dto.getId())) {
            throw new RuntimeException("Capacidadexepcional ya existe con id: " + dto.getId());
        }
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public CapacidadexepcionalDTO update(Integer id, CapacidadexepcionalDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Capacidadexepcional no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Capacidadexepcional no encontrado con id: " + id));
        repository.deleteById(id);
    }
}