/*
 * Created on 2026-05-18 ( 01:57:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.*;
import ufps.edu.co.persistence.repositories.*;
import ufps.edu.co.rest.dto.*;
import ufps.edu.co.rest.services.commons.*;

/**
 * REST service for entity "Capacidadexepcional" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class CapacidadexepcionalService extends GenericService<CapacidadexepcionalEntity, CapacidadexepcionalDTO> {

    @Autowired
    private CapacidadexepcionalRepository repository;

    public CapacidadexepcionalService() {
        super(CapacidadexepcionalEntity.class, CapacidadexepcionalDTO.class);
    }

    @Transactional(readOnly = true)
    public List<CapacidadexepcionalDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public CapacidadexepcionalDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public CapacidadexepcionalDTO create(CapacidadexepcionalDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public CapacidadexepcionalDTO update(Integer id, CapacidadexepcionalDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Capacidadexepcional no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Capacidadexepcional no encontrado con id: " + id));
        repository.deleteById(id);
    }

    @Transactional(readOnly = true)
    public CapacidadexepcionalDTO findByNombre(String nombre) {
        return entityToDto(repository.findByTipocapacidadIgnoreCase(nombre));
    }
}