/*
 * Created on 2026-05-14 ( 22:37:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.CriterioaceptacionEntity;
import ufps.edu.co.persistence.repositories.CriterioaceptacionRepository;
import ufps.edu.co.rest.dto.CriterioaceptacionDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Criterioaceptacion" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class CriterioaceptacionService extends GenericService<CriterioaceptacionEntity, CriterioaceptacionDTO> {

    @Autowired
    private CriterioaceptacionRepository repository;

    public CriterioaceptacionService() {
        super(CriterioaceptacionEntity.class, CriterioaceptacionDTO.class);
    }

    @Transactional(readOnly = true)
    public List<CriterioaceptacionDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public CriterioaceptacionDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public CriterioaceptacionDTO create(CriterioaceptacionDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public CriterioaceptacionDTO update(Integer id, CriterioaceptacionDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Criterioaceptacion no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Criterioaceptacion no encontrado con id: " + id));
        repository.deleteById(id);
    }
}