/*
 * Created on 2026-05-24 ( 03:25:12 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.*;
import org.springframework.beans.factory.annotation.*;
import org.springframework.stereotype.*;
import org.springframework.transaction.annotation.*;
import ufps.edu.co.persistence.entities.*;
import ufps.edu.co.persistence.projections.*;
import ufps.edu.co.persistence.repositories.*;
import ufps.edu.co.rest.dto.*;
import ufps.edu.co.rest.services.commons.*;

/**
 * REST service for entity "Criteriocohorte" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class CriteriocohorteService extends GenericService<CriteriocohorteEntity, CriteriocohorteDTO> {

    @Autowired
    private CriteriocohorteRepository repository;

    public CriteriocohorteService() {
        super(CriteriocohorteEntity.class, CriteriocohorteDTO.class);
    }

    @Override
    protected CriteriocohorteDTO entityToDto(CriteriocohorteEntity e) {
        return CriteriocohorteDTO.builder()
                .id(e.getId())
                .pesoSnapshot(e.getPesoSnapshot())
                .idCohorte(e.getIdCohorte())
                .idCriterio(e.getIdCriterio())
                .build();
    }

    @Transactional(readOnly = true)
    public List<CriteriocohorteDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public CriteriocohorteDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public CriteriocohorteDTO create(CriteriocohorteDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public CriteriocohorteDTO update(Integer id, CriteriocohorteDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Criteriocohorte no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Criteriocohorte no encontrado con id: " + id));
        repository.deleteById(id);
    }

    @Transactional(readOnly = true)
    public List<CriteriocohorteDTO> findByIdCohorte(Integer idCohorte) {
        return entityListToDtoList(repository.findByIdCohorte(idCohorte));
    }

    @Transactional(readOnly = true)
    public List<CriteriocohorteDTO> findByIdCriterio(Integer idCriterio) {
        return entityListToDtoList(repository.findByIdCriterio(idCriterio));
    }

    @Transactional(readOnly = true)
    public List<CriterioCalificacionView> findCriteriosConCalificacion(Integer idCohorte, Integer idAspirante) {
        return repository.findCriteriosConCalificacion(idCohorte, idAspirante);
    }
}