/*
 * Created on 2026-05-14 ( 22:37:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DiscapacidadEntity;
import ufps.edu.co.persistence.repositories.DiscapacidadRepository;
import ufps.edu.co.rest.dto.DiscapacidadDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Discapacidad" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DiscapacidadService extends GenericService<DiscapacidadEntity, DiscapacidadDTO> {

    @Autowired
    private DiscapacidadRepository repository;

    public DiscapacidadService() {
        super(DiscapacidadEntity.class, DiscapacidadDTO.class);
    }

    @Transactional(readOnly = true)
    public List<DiscapacidadDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public DiscapacidadDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public DiscapacidadDTO create(DiscapacidadDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public DiscapacidadDTO update(Integer id, DiscapacidadDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Discapacidad no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Discapacidad no encontrado con id: " + id));
        repository.deleteById(id);
    }
}