/*
 * Created on 2026-05-24 ( 17:03:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DocumentoEntity;
import ufps.edu.co.persistence.repositories.DocumentoRepository;
import ufps.edu.co.rest.dto.DocumentoDTO;
import ufps.edu.co.rest.dto.EstadodocumentoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Documento" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DocumentoService extends GenericService<DocumentoEntity, DocumentoDTO> {

    @Autowired
    private DocumentoRepository repository;

    public DocumentoService() {
        super(DocumentoEntity.class, DocumentoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<DocumentoDTO> findAll() {
        return repository.findAllScalar().stream().map(this::rowToDto).toList();
    }

    @Transactional(readOnly = true)
    public DocumentoDTO findById(Integer id) {
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public DocumentoDTO create(DocumentoDTO dto) {
        Integer id = repository.save(dtoToEntity(dto)).getId();
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public DocumentoDTO update(Integer id, DocumentoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documento no encontrado con id: " + id));
        dto.setId(id);
        repository.save(dtoToEntity(dto));
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documento no encontrado con id: " + id));
        repository.deleteById(id);
    }

    @Transactional(readOnly = true)
    public List<DocumentoDTO> findByIdAspirante(Integer idAspirante) {
        return repository.findByIdAspiranteScalar(idAspirante).stream().map(this::rowToDto).toList();
    }

    @Transactional(readOnly = true)
    public Optional<DocumentoDTO> findByIdAspiranteAndIdDocumentosrequisitoconsejocohorte(Integer idAspirante,
            Integer idDocumentosrequisitoconsejocohorte) {
        return repository
                .findByIdAspiranteAndIdDocumentosrequisitoconsejocohorteScalar(idAspirante, idDocumentosrequisitoconsejocohorte)
                .map(this::rowToDto);
    }

    @Transactional(readOnly = true)
    public Optional<DocumentoDTO> findByIdAspiranteAndIdDocumentosrequisitoprogramacohorte(Integer idAspirante,
            Integer idDocumentosrequisitoprogramacohorte) {
        return repository
                .findByIdAspiranteAndIdDocumentosrequisitoprogramacohorteScalar(idAspirante, idDocumentosrequisitoprogramacohorte)
                .map(this::rowToDto);
    }

    private DocumentoDTO rowToDto(Object[] row) {
        // [0]=id [1]=enlaceurl [2]=fechacargue [3]=keyfile [4]=observaciones
        // [5]=idAdministrativo [6]=idAspirante [7]=idEstadodocumento [8]=idPlazo
        // [9]=idDocumentosrequisitoconsejocohorte [10]=idDocumentosrequisitoprogramacohorte
        // [11]=estadodocumento.estado
        EstadodocumentoDTO estadodocumentoDto = row[7] != null ? EstadodocumentoDTO.builder()
                .id((Integer) row[7])
                .estado((String) row[11])
                .build() : null;
        return DocumentoDTO.builder()
                .id((Integer) row[0])
                .enlaceurl((String) row[1])
                .fechacargue((LocalDate) row[2])
                .keyfile((String) row[3])
                .observaciones((String) row[4])
                .idAdministrativo((Integer) row[5])
                .idAspirante((Integer) row[6])
                .idEstadodocumento((Integer) row[7])
                .idPlazo((Integer) row[8])
                .idDocumentosrequisitoconsejocohorte((Integer) row[9])
                .idDocumentosrequisitoprogramacohorte((Integer) row[10])
                .estadodocumento(estadodocumentoDto)
                .build();
    }
}
