/*
 * Created on 2026-05-24 ( 17:03:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DocumentosrequisitoprogramaEntity;
import ufps.edu.co.persistence.repositories.DocumentosrequisitoprogramaRepository;
import ufps.edu.co.rest.dto.DocumentosrequisitoprogramaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Documentosrequisitoprograma" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DocumentosrequisitoprogramaService extends GenericService<DocumentosrequisitoprogramaEntity, DocumentosrequisitoprogramaDTO> {

    @Autowired
    private DocumentosrequisitoprogramaRepository repository;

    public DocumentosrequisitoprogramaService() {
        super(DocumentosrequisitoprogramaEntity.class, DocumentosrequisitoprogramaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoprogramaDTO> findAll() {
        return repository.findAll().stream().map(this::mapEntityToDto).toList();
    }

    @Transactional(readOnly = true)
    public DocumentosrequisitoprogramaDTO findById(Integer id) {
        return repository.findById(id).map(this::mapEntityToDto).orElse(null);
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoprogramaDTO> findByIdPrograma(Integer idPrograma) {
        return repository.findByIdPrograma(idPrograma).stream().map(this::mapEntityToDto).toList();
    }

    public DocumentosrequisitoprogramaDTO create(DocumentosrequisitoprogramaDTO dto) {
        DocumentosrequisitoprogramaEntity saved = repository.save(mapDtoToEntity(dto));
        return mapEntityToDto(saved);
    }

    public DocumentosrequisitoprogramaDTO update(Integer id, DocumentosrequisitoprogramaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoprograma no encontrado con id: " + id));
        dto.setId(id);
        DocumentosrequisitoprogramaEntity saved = repository.save(mapDtoToEntity(dto));
        return mapEntityToDto(saved);
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoprograma no encontrado con id: " + id));
        repository.deleteById(id);
    }

    private DocumentosrequisitoprogramaDTO rowToDto(Object[] row) {
        return DocumentosrequisitoprogramaDTO.builder()
                .id((Integer) row[0])
                .nombre((String) row[1])
                .tamanomaximo((Integer) row[2])
                .urlformato((String) row[3])
                .id_programa((Integer) row[4])
                .build();
    }

    private DocumentosrequisitoprogramaEntity mapDtoToEntity(DocumentosrequisitoprogramaDTO dto) {
        if (dto == null) {
            return null;
        }
        return DocumentosrequisitoprogramaEntity.builder()
                .id(dto.getId())
                .nombre(dto.getNombre())
                .tamanomaximo(dto.getTamanomaximo())
                .urlformato(dto.getUrlformato())
                .idPrograma(dto.getId_programa())
                .build();
    }

    private DocumentosrequisitoprogramaDTO mapEntityToDto(DocumentosrequisitoprogramaEntity entity) {
        if (entity == null) {
            return null;
        }
        return DocumentosrequisitoprogramaDTO.builder()
                .id(entity.getId())
                .nombre(entity.getNombre())
                .tamanomaximo(entity.getTamanomaximo())
                .urlformato(entity.getUrlformato())
                .id_programa(entity.getIdPrograma())
                .build();
    }
}
