/*
 * Created on 2026-05-24 ( 17:03:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DocumentoEntity;
import ufps.edu.co.persistence.repositories.DocumentoRepository;
import ufps.edu.co.rest.dto.DocumentoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Documento" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DocumentoService extends GenericService<DocumentoEntity, DocumentoDTO> {

    @Autowired
    private DocumentoRepository repository;

    public DocumentoService() {
        super(DocumentoEntity.class, DocumentoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<DocumentoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public DocumentoDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public DocumentoDTO create(DocumentoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public DocumentoDTO update(Integer id, DocumentoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documento no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documento no encontrado con id: " + id));
        repository.deleteById(id);
    }

    @Transactional(readOnly = true)
    public List<DocumentoDTO> findByIdAspirante(Integer idAspirante) {
        return entityListToDtoList(repository.findByIdAspirante(idAspirante));
    }

    @Transactional(readOnly = true)
    public Optional<DocumentoDTO> findByIdAspiranteAndIdDocumentosrequisitoconsejocohorte(Integer idAspirante,
            Integer idDocumentosrequisitoconsejocohorte) {
        return repository
                .findByIdAspiranteAndIdDocumentosrequisitoconsejocohorte(idAspirante, idDocumentosrequisitoconsejocohorte)
                .map(this::entityToDto);
    }

    @Transactional(readOnly = true)
    public Optional<DocumentoDTO> findByIdAspiranteAndIdDocumentosrequisitoprogramacohorte(Integer idAspirante,
            Integer idDocumentosrequisitoprogramacohorte) {
        return repository
                .findByIdAspiranteAndIdDocumentosrequisitoprogramacohorte(idAspirante, idDocumentosrequisitoprogramacohorte)
                .map(this::entityToDto);
    }
}
