/*
 * Created on 2026-05-24 ( 17:03:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DocumentosrequisitoconsejocohorteEntity;
import ufps.edu.co.persistence.repositories.DocumentosrequisitoconsejocohorteRepository;
import ufps.edu.co.rest.dto.DocumentosrequisitoconsejocohorteDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Documentosrequisitoconsejocohorte" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DocumentosrequisitoconsejocohorteService extends GenericService<DocumentosrequisitoconsejocohorteEntity, DocumentosrequisitoconsejocohorteDTO> {

    @Autowired
    private DocumentosrequisitoconsejocohorteRepository repository;

    public DocumentosrequisitoconsejocohorteService() {
        super(DocumentosrequisitoconsejocohorteEntity.class, DocumentosrequisitoconsejocohorteDTO.class);
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoconsejocohorteDTO> findAll() {
        return repository.findAllScalar().stream().map(this::rowToDto).toList();
    }

    @Transactional(readOnly = true)
    public DocumentosrequisitoconsejocohorteDTO findById(Integer id) {
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoconsejocohorteDTO> findByIdCohorte(Integer idCohorte) {
        return repository.findByIdCohorteScalar(idCohorte).stream().map(this::rowToDto).toList();
    }

    public DocumentosrequisitoconsejocohorteDTO create(DocumentosrequisitoconsejocohorteDTO dto) {
        Integer id = repository.save(dtoToEntity(dto)).getId();
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public DocumentosrequisitoconsejocohorteDTO update(Integer id, DocumentosrequisitoconsejocohorteDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoconsejocohorte no encontrado con id: " + id));
        dto.setId(id);
        repository.save(dtoToEntity(dto));
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoconsejocohorte no encontrado con id: " + id));
        repository.deleteById(id);
    }

    private DocumentosrequisitoconsejocohorteDTO rowToDto(Object[] row) {
        return DocumentosrequisitoconsejocohorteDTO.builder()
                .id((Integer) row[0])
                .idDocrequisito((Integer) row[1])
                .idCohorte((Integer) row[2])
                .build();
    }
}
