/*
 * Created on 2026-05-24 ( 17:03:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DocumentosrequisitoprogramaEntity;
import ufps.edu.co.persistence.repositories.DocumentosrequisitoprogramaRepository;
import ufps.edu.co.rest.dto.DocumentosrequisitoprogramaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Documentosrequisitoprograma" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DocumentosrequisitoprogramaService extends GenericService<DocumentosrequisitoprogramaEntity, DocumentosrequisitoprogramaDTO> {

    @Autowired
    private DocumentosrequisitoprogramaRepository repository;

    public DocumentosrequisitoprogramaService() {
        super(DocumentosrequisitoprogramaEntity.class, DocumentosrequisitoprogramaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoprogramaDTO> findAll() {
        return repository.findAllScalar().stream().map(this::rowToDto).toList();
    }

    @Transactional(readOnly = true)
    public DocumentosrequisitoprogramaDTO findById(Integer id) {
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoprogramaDTO> findByIdPrograma(Integer idPrograma) {
        return repository.findByIdProgramaScalar(idPrograma).stream().map(this::rowToDto).toList();
    }

    public DocumentosrequisitoprogramaDTO create(DocumentosrequisitoprogramaDTO dto) {
        Integer id = repository.save(dtoToEntity(dto)).getId();
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public DocumentosrequisitoprogramaDTO update(Integer id, DocumentosrequisitoprogramaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoprograma no encontrado con id: " + id));
        dto.setId(id);
        repository.save(dtoToEntity(dto));
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoprograma no encontrado con id: " + id));
        repository.deleteById(id);
    }

    private DocumentosrequisitoprogramaDTO rowToDto(Object[] row) {
        return DocumentosrequisitoprogramaDTO.builder()
                .id((Integer) row[0])
                .nombre((String) row[1])
                .tamanomaximo((Integer) row[2])
                .build();
    }
}
