/*
 * Created on 2026-05-21 ( 15:00:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DocumentocohorteEntity;
import ufps.edu.co.persistence.repositories.DocumentocohorteRepository;
import ufps.edu.co.rest.dto.DocumentocohorteDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Documentocohorte" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DocumentocohorteService extends GenericService<DocumentocohorteEntity, DocumentocohorteDTO> {

    @Autowired
    private DocumentocohorteRepository repository;

    public DocumentocohorteService() {
        super(DocumentocohorteEntity.class, DocumentocohorteDTO.class);
    }

    @Transactional(readOnly = true)
    public List<DocumentocohorteDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public DocumentocohorteDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public DocumentocohorteDTO create(DocumentocohorteDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public DocumentocohorteDTO update(Integer id, DocumentocohorteDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentocohorte no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentocohorte no encontrado con id: " + id));
        repository.deleteById(id);
    }

    public List<DocumentocohorteDTO> findByIdCohorte(Integer idCohorte) {
        return entityListToDtoList(repository.findByIdCohorte(idCohorte));
    }
}