/*
 * Created on 2026-05-24 ( 17:03:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DocumentosrequisitoconsejoEntity;
import ufps.edu.co.persistence.repositories.DocumentosrequisitoconsejoRepository;
import ufps.edu.co.rest.dto.DocumentosrequisitoconsejoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Documentosrequisitoconsejo" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DocumentosrequisitoconsejoService extends GenericService<DocumentosrequisitoconsejoEntity, DocumentosrequisitoconsejoDTO> {

    @Autowired
    private DocumentosrequisitoconsejoRepository repository;

    public DocumentosrequisitoconsejoService() {
        super(DocumentosrequisitoconsejoEntity.class, DocumentosrequisitoconsejoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoconsejoDTO> findAll() {
        return repository.findAllScalar().stream().map(this::rowToDto).toList();
    }

    @Transactional(readOnly = true)
    public DocumentosrequisitoconsejoDTO findById(Integer id) {
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public DocumentosrequisitoconsejoDTO create(DocumentosrequisitoconsejoDTO dto) {
        Integer id = repository.save(dtoToEntity(dto)).getId();
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public DocumentosrequisitoconsejoDTO update(Integer id, DocumentosrequisitoconsejoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoconsejo no encontrado con id: " + id));
        dto.setId(id);
        repository.save(dtoToEntity(dto));
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoconsejo no encontrado con id: " + id));
        repository.deleteById(id);
    }

    private DocumentosrequisitoconsejoDTO rowToDto(Object[] row) {
        return DocumentosrequisitoconsejoDTO.builder()
                .id((Integer) row[0])
                .nombre((String) row[1])
                .tamanomaximo((Integer) row[2])
                .build();
    }
}
