/*
 * Created on 2026-05-18 ( 01:57:51 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.EntrevistaEntity;
import ufps.edu.co.persistence.repositories.EntrevistaRepository;
import ufps.edu.co.rest.dto.EntrevistaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Entrevista" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class EntrevistaService extends GenericService<EntrevistaEntity, EntrevistaDTO> {

    @Autowired
    private EntrevistaRepository repository;

    public EntrevistaService() {
        super(EntrevistaEntity.class, EntrevistaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<EntrevistaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public EntrevistaDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public EntrevistaDTO create(EntrevistaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public EntrevistaDTO update(Integer id, EntrevistaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrado con id: " + id));
        repository.deleteById(id);
    }

    @Transactional(readOnly = true)
    public List<EntrevistaDTO> findByIdAspirante(Integer idAspirante) {
        return entityListToDtoList(repository.findByIdAspirante(idAspirante));
    }

    public EntrevistaDTO changeEstado(Integer id, Integer idEstado, String expectedCurrentEstado) {
        EntrevistaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        String estadoActual = entity.getEstado() != null ? entity.getEstado().getTipo() : "";
        if (!expectedCurrentEstado.equalsIgnoreCase(estadoActual)) {
            throw new RuntimeException(
                    "La entrevista no está en estado '" + expectedCurrentEstado + "'. Estado actual: " + estadoActual);
        }
        entity.setIdEstado(idEstado);
        return entityToDto(repository.save(entity));
    }

    public EntrevistaDTO reschedule(Integer id, LocalDate fecha, LocalTime tiempo,
            Integer idTipoentrevista, Integer idUbicacion) {
        EntrevistaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        String estadoTipo = entity.getEstado() != null ? entity.getEstado().getTipo() : "";
        if (!"SOLICITUD_CAMBIO".equalsIgnoreCase(estadoTipo)) {
            throw new RuntimeException("Solo se puede reagendar una entrevista en estado 'Solicitud de cambio'");
        }
        entity.setFecha(fecha);
        entity.setTiempo(tiempo);
        entity.setIdTipoentrevista(idTipoentrevista);
        entity.setIdUbicacion(idUbicacion);
        return entityToDto(repository.save(entity));
    }

    public EntrevistaDTO rateInterview(Integer id, BigDecimal calificacion) {
        EntrevistaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        entity.setCalificacion(calificacion);
        return entityToDto(repository.save(entity));
    }
}