/*
 * Created on 2026-05-18 ( 01:57:51 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.EntrevistaEntity;
import ufps.edu.co.persistence.repositories.EntrevistaRepository;
import ufps.edu.co.persistence.repositories.EstadoRepository;
import ufps.edu.co.rest.dto.EntrevistaDTO;
import ufps.edu.co.rest.dto.EstadoDTO;
import ufps.edu.co.rest.dto.TipoentrevistaDTO;
import ufps.edu.co.rest.dto.UbicacionDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Entrevista" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class EntrevistaService extends GenericService<EntrevistaEntity, EntrevistaDTO> {

    @Autowired
    private EntrevistaRepository repository;

    @Autowired
    private EstadoRepository estadoRepository;

    public EntrevistaService() {
        super(EntrevistaEntity.class, EntrevistaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<EntrevistaDTO> findAll() {
        return repository.findAllScalar().stream().map(this::rowToDto).toList();
    }

    @Transactional(readOnly = true)
    public EntrevistaDTO findById(Integer id) {
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public EntrevistaDTO create(EntrevistaDTO dto) {
        Integer id = repository.save(dtoToEntity(dto)).getId();
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public EntrevistaDTO update(Integer id, EntrevistaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrado con id: " + id));
        dto.setId(id);
        repository.save(dtoToEntity(dto));
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrado con id: " + id));
        repository.deleteById(id);
    }

    @Transactional(readOnly = true)
    public List<EntrevistaDTO> findByIdAspirante(Integer idAspirante) {
        return repository.findByIdAspiranteScalar(idAspirante).stream().map(this::rowToDto).toList();
    }

    public EntrevistaDTO changeEstado(Integer id, Integer idEstado, String expectedCurrentEstado) {
        EntrevistaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        String estadoActual = entity.getEstado() != null ? entity.getEstado().getTipo() : "";
        if (!expectedCurrentEstado.equalsIgnoreCase(estadoActual)) {
            throw new RuntimeException(
                    "La entrevista no está en estado '" + expectedCurrentEstado + "'. Estado actual: " + estadoActual);
        }
        entity.setIdEstado(idEstado);
        repository.save(entity);
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public EntrevistaDTO changeEstadoWithMotivo(Integer id, Integer idEstado, String expectedCurrentEstado, String motivocambio) {
        EntrevistaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        String estadoActual = entity.getEstado() != null ? entity.getEstado().getTipo() : "";
        if (!expectedCurrentEstado.equalsIgnoreCase(estadoActual)) {
            throw new RuntimeException(
                    "La entrevista no está en estado '" + expectedCurrentEstado + "'. Estado actual: " + estadoActual);
        }
        entity.setIdEstado(idEstado);
        entity.setMotivocambio(motivocambio);
        repository.save(entity);
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public EntrevistaDTO reschedule(Integer id, LocalDate fecha, LocalTime tiempo,
            Integer idTipoentrevista, Integer idUbicacion, String motivocambio) {
        EntrevistaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        String estadoActual = entity.getEstado() != null ? entity.getEstado().getTipo() : "";
        if (!"SOLICITUD DE CAMBIO".equalsIgnoreCase(estadoActual)) {
            throw new IllegalStateException(
                    "La entrevista no está en estado 'SOLICITUD DE CAMBIO'. Estado actual: " + estadoActual);
        }
        Integer idEstadoPendiente = estadoRepository
                .findByTipoIgnoreCaseAndEntidadIgnoreCase("PENDIENTE DE CONFIRMACION", "entrevista")
                .orElseThrow(() -> new RuntimeException("Estado 'PENDIENTE DE CONFIRMACION' no encontrado para entidad 'entrevista'"))
                .getId();
        entity.setFecha(fecha);
        entity.setTiempo(tiempo);
        entity.setIdTipoentrevista(idTipoentrevista);
        entity.setIdUbicacion(idUbicacion);
        entity.setIdEstado(idEstadoPendiente);
        entity.setMotivocambio(motivocambio);
        repository.save(entity);
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public EntrevistaDTO rateInterview(Integer id, BigDecimal calificacion) {
        EntrevistaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        // TODO: asignar calificacion en la entidad cuando el campo exista
        repository.save(entity);
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public EntrevistaDTO requestChange(Integer id, String motivocambio) {
        EntrevistaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        String estadoActual = entity.getEstado() != null ? entity.getEstado().getTipo() : "";
        if (!"PENDIENTE DE CONFIRMACION".equalsIgnoreCase(estadoActual)) {
            throw new RuntimeException(
                    "La entrevista no está en estado 'PENDIENTE DE CONFIRMACION'. Estado actual: " + estadoActual);
        }
        Integer idEstadoSolicitud = estadoRepository
                .findByTipoIgnoreCaseAndEntidadIgnoreCase("SOLICITUD DE CAMBIO", "entrevista")
                .orElseThrow(() -> new RuntimeException(
                        "Estado 'SOLICITUD DE CAMBIO' no encontrado para entidad 'entrevista'"))
                .getId();
        entity.setIdEstado(idEstadoSolicitud);
        entity.setMotivocambio(motivocambio);
        repository.save(entity);
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    private EntrevistaDTO rowToDto(Object[] row) {
        // [0]=id [1]=fecha [2]=tiempo [3]=motivocambio
        // [4]=idAspirante [5]=idEstado [6]=idTipoentrevista [7]=idUbicacion
        // [8]=estado.tipo [9]=estado.entidad
        // [10]=tipoentrevista.tipo [11]=tipoentrevista.descripcion
        // [12]=ubicacion.direccion
        EstadoDTO estadoDto = row[5] != null ? EstadoDTO.builder()
                .id((Integer) row[5])
                .tipo((String) row[8])
                .entidad((String) row[9])
                .build() : null;
        TipoentrevistaDTO tipoentrevistaDto = row[6] != null ? TipoentrevistaDTO.builder()
                .id((Integer) row[6])
                .tipo((String) row[10])
                .descripcion((String) row[11])
                .build() : null;
        UbicacionDTO ubicacionDto = row[7] != null ? UbicacionDTO.builder()
                .id((Integer) row[7])
                .direccion((String) row[12])
                .build() : null;
        return EntrevistaDTO.builder()
                .id((Integer) row[0])
                .fecha((LocalDate) row[1])
                .tiempo((LocalTime) row[2])
                .motivocambio((String) row[3])
                .idAspirante((Integer) row[4])
                .idEstado((Integer) row[5])
                .idTipoentrevista((Integer) row[6])
                .idUbicacion((Integer) row[7])
                .estado(estadoDto)
                .tipoentrevista(tipoentrevistaDto)
                .ubicacion(ubicacionDto)
                .build();
    }
}
