/*
 * Created on 2026-05-18 ( 01:57:52 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.EstadodocumentoEntity;
import ufps.edu.co.persistence.repositories.EstadodocumentoRepository;
import ufps.edu.co.rest.dto.EstadodocumentoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Estadodocumento" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class EstadodocumentoService extends GenericService<EstadodocumentoEntity, EstadodocumentoDTO> {

    @Autowired
    private EstadodocumentoRepository repository;

    public EstadodocumentoService() {
        super(EstadodocumentoEntity.class, EstadodocumentoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<EstadodocumentoDTO> findAll() {
        return repository.findAllScalar().stream().map(this::rowToDto).toList();
    }

    @Transactional(readOnly = true)
    public EstadodocumentoDTO findById(Integer id) {
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    @Transactional(readOnly = true)
    public EstadodocumentoDTO findByEstado(String estado) {
        return repository.findByEstadoScalar(estado)
                .map(this::rowToDto)
                .orElseThrow(() -> new RuntimeException("Estado de documento no encontrado: " + estado));
    }

    public EstadodocumentoDTO create(EstadodocumentoDTO dto) {
        Integer id = repository.save(dtoToEntity(dto)).getId();
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public EstadodocumentoDTO update(Integer id, EstadodocumentoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Estadodocumento no encontrado con id: " + id));
        dto.setId(id);
        repository.save(dtoToEntity(dto));
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Estadodocumento no encontrado con id: " + id));
        repository.deleteById(id);
    }

    private EstadodocumentoDTO rowToDto(Object[] row) {
        return EstadodocumentoDTO.builder()
                .id((Integer) row[0])
                .estado((String) row[1])
                .build();
    }
}
