/*
 * Created on 2026-05-18 ( 01:57:52 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.FacultadEntity;
import ufps.edu.co.persistence.repositories.FacultadRepository;
import ufps.edu.co.rest.dto.FacultadDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Facultad" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class FacultadService extends GenericService<FacultadEntity, FacultadDTO> {

    @Autowired
    private FacultadRepository repository;

    public FacultadService() {
        super(FacultadEntity.class, FacultadDTO.class);
    }

    @Transactional(readOnly = true)
    public List<FacultadDTO> findAll() {
        return repository.findAllScalar().stream().map(this::rowToDto).toList();
    }

    @Transactional(readOnly = true)
    public FacultadDTO findById(Integer id) {
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public FacultadDTO create(FacultadDTO dto) {
        Integer id = repository.save(dtoToEntity(dto)).getId();
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public FacultadDTO update(Integer id, FacultadDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Facultad no encontrado con id: " + id));
        dto.setId(id);
        repository.save(dtoToEntity(dto));
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Facultad no encontrado con id: " + id));
        repository.deleteById(id);
    }

    private FacultadDTO rowToDto(Object[] row) {
        return FacultadDTO.builder()
                .id((Integer) row[0])
                .nombre((String) row[1])
                .correo((String) row[2])
                .build();
    }
}
