/*
 * Created on 2026-05-14 ( 22:38:00 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import java.util.Optional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import ufps.edu.co.persistence.entities.AdmitidoEntity;
import ufps.edu.co.persistence.repositories.AdmitidoRepository;
import ufps.edu.co.rest.dto.AdmitidoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Listaadmitidos" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class ListaadmitidosService extends GenericService<AdmitidoEntity, AdmitidoDTO> {

    @Autowired
    private AdmitidoRepository repository;

    public ListaadmitidosService() {
        super(AdmitidoEntity.class, AdmitidoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<AdmitidoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public AdmitidoDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public AdmitidoDTO create(AdmitidoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public AdmitidoDTO update(Integer id, AdmitidoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Admitido no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Admitido no encontrado con id: " + id));
        repository.deleteById(id);
    }

    @Transactional(readOnly = true)
    public List<AdmitidoDTO> findByIdCohorte(Integer idCohorte) {
        return entityListToDtoList(repository.findByIdCohorte(idCohorte));
    }

    @Transactional(readOnly = true)
    public Optional<AdmitidoDTO> findByIdCohorteAndIdAspirante(Integer idCohorte, Integer idAspirante) {
        return repository.findByIdCohorteAndIdAspirante(idCohorte, idAspirante)
                .map(entity -> entityToDto(entity));
    }

    @Transactional(readOnly = true)
    public boolean existsByIdCohorteAndIdAspirante(Integer idCohorte, Integer idAspirante) {
        return repository.existsByIdCohorteAndIdAspirante(idCohorte, idAspirante);
    }

    public void deleteByIdCohorteAndIdAspirante(Integer idCohorte, Integer idAspirante) {
        AdmitidoEntity entity = repository.findByIdCohorteAndIdAspirante(idCohorte, idAspirante)
                .orElseThrow(() -> new RuntimeException(
                        "Admitido no encontrado para cohorte: " + idCohorte + ", aspirante: " + idAspirante));
        repository.deleteById(entity.getId());
    }
}