/*
 * Created on 2026-05-18 ( 01:57:52 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.ModalidadEntity;
import ufps.edu.co.persistence.repositories.ModalidadRepository;
import ufps.edu.co.rest.dto.ModalidadDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Modalidad" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class ModalidadService extends GenericService<ModalidadEntity, ModalidadDTO> {

    @Autowired
    private ModalidadRepository repository;

    public ModalidadService() {
        super(ModalidadEntity.class, ModalidadDTO.class);
    }

    @Transactional(readOnly = true)
    public List<ModalidadDTO> findAll() {
        return repository.findAllScalar().stream().map(this::rowToDto).toList();
    }

    @Transactional(readOnly = true)
    public ModalidadDTO findById(Integer id) {
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public ModalidadDTO create(ModalidadDTO dto) {
        Integer id = repository.save(dtoToEntity(dto)).getId();
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public ModalidadDTO update(Integer id, ModalidadDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Modalidad no encontrado con id: " + id));
        dto.setId(id);
        repository.save(dtoToEntity(dto));
        return repository.findByIdScalar(id).map(this::rowToDto).orElse(null);
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Modalidad no encontrado con id: " + id));
        repository.deleteById(id);
    }

    private ModalidadDTO rowToDto(Object[] row) {
        return ModalidadDTO.builder()
                .id((Integer) row[0])
                .nombre((String) row[1])
                .build();
    }
}
