/*
 * Created on 2026-05-14 ( 22:04:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.PagoEntity;
import ufps.edu.co.persistence.repositories.PagoRepository;
import ufps.edu.co.rest.dto.PagoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Pago" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class PagoService extends GenericService<PagoEntity, PagoDTO> {

    @Autowired
    private PagoRepository repository;

    public PagoService() {
        super(PagoEntity.class, PagoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<PagoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public PagoDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public PagoDTO create(PagoDTO dto) {
        if (repository.existsById(dto.getId())) {
            throw new RuntimeException("Pago ya existe con id: " + dto.getId());
        }
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public PagoDTO update(Integer id, PagoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Pago no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Pago no encontrado con id: " + id));
        repository.deleteById(id);
    }
}