/*
 * Created on 2026-05-14 ( 22:04:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.PagoconceptoEntity;
import ufps.edu.co.persistence.repositories.PagoconceptoRepository;
import ufps.edu.co.rest.dto.PagoconceptoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Pagoconcepto" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class PagoconceptoService extends GenericService<PagoconceptoEntity, PagoconceptoDTO> {

    @Autowired
    private PagoconceptoRepository repository;

    public PagoconceptoService() {
        super(PagoconceptoEntity.class, PagoconceptoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<PagoconceptoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public PagoconceptoDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public PagoconceptoDTO create(PagoconceptoDTO dto) {
        if (repository.existsById(dto.getId())) {
            throw new RuntimeException("Pagoconcepto ya existe con id: " + dto.getId());
        }
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public PagoconceptoDTO update(Integer id, PagoconceptoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Pagoconcepto no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Pagoconcepto no encontrado con id: " + id));
        repository.deleteById(id);
    }
}