/*
 * Created on 2026-05-10 ( 01:19:10 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.PagosEntity;
import ufps.edu.co.persistence.repositories.PagosRepository;
import ufps.edu.co.rest.dto.PagosDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Pagos" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class PagosService extends GenericService<PagosEntity, PagosDTO> {

    @Autowired
    private PagosRepository repository;

    public PagosService() {
        super(PagosEntity.class, PagosDTO.class);
    }

    @Transactional(readOnly = true)
    public List<PagosDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public PagosDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public PagosDTO create(PagosDTO dto) {
        if (repository.existsById(dto.getId())) {
            throw new RuntimeException("Pagos ya existe con id: " + dto.getId());
        }
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public PagosDTO update(Integer id, PagosDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Pagos no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Pagos no encontrado con id: " + id));
        repository.deleteById(id);
    }
}