/*
 * Created on 2026-05-14 ( 22:38:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.PoblacionindigenaEntity;
import ufps.edu.co.persistence.repositories.PoblacionindigenaRepository;
import ufps.edu.co.rest.dto.PoblacionindigenaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Poblacionindigena" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class PoblacionindigenaService extends GenericService<PoblacionindigenaEntity, PoblacionindigenaDTO> {

    @Autowired
    private PoblacionindigenaRepository repository;

    public PoblacionindigenaService() {
        super(PoblacionindigenaEntity.class, PoblacionindigenaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<PoblacionindigenaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public PoblacionindigenaDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public PoblacionindigenaDTO create(PoblacionindigenaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public PoblacionindigenaDTO update(Integer id, PoblacionindigenaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Poblacionindigena no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Poblacionindigena no encontrado con id: " + id));
        repository.deleteById(id);
    }
}