/*
 * Created on 2026-05-18 ( 01:57:54 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.PruebaEntity;
import ufps.edu.co.persistence.repositories.EstadoRepository;
import ufps.edu.co.persistence.repositories.PruebaRepository;
import ufps.edu.co.rest.dto.EstadoDTO;
import ufps.edu.co.rest.dto.PruebaDTO;
import ufps.edu.co.rest.dto.TipopruebaDTO;
import ufps.edu.co.rest.dto.UbicacionDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Prueba" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class PruebaService extends GenericService<PruebaEntity, PruebaDTO> {

    @Autowired
    private PruebaRepository repository;

    @Autowired
    private EstadoRepository estadoRepository;

    public PruebaService() {
        super(PruebaEntity.class, PruebaDTO.class);
    }

    @Override
    protected PruebaDTO entityToDto(PruebaEntity e) {
        UbicacionDTO ubicacionDto = e.getUbicacion() != null ? UbicacionDTO.builder()
                .id(e.getUbicacion().getId())
                .direccion(e.getUbicacion().getDireccion())
                .build() : null;
        EstadoDTO estadoDto = e.getEstado() != null ? EstadoDTO.builder()
                .id(e.getEstado().getId())
                .tipo(e.getEstado().getTipo())
                .build() : null;
        TipopruebaDTO tipopruebaDto = e.getTipoprueba() != null ? TipopruebaDTO.builder()
                .id(e.getTipoprueba().getId())
                .tipo(e.getTipoprueba().getTipo())
                .build() : null;
        return PruebaDTO.builder()
                .id(e.getId())
                .nombre(e.getNombre())
                .descripcion(e.getDescripcion())
                .fecha(e.getFecha())
                .tiempo(e.getTiempo())
                .motivocambio(e.getMotivocambio())
                .idAspirante(e.getIdAspirante())
                .idCohorte(e.getIdCohorte())
                .idUbicacion(e.getIdUbicacion())
                .idEstado(e.getIdEstado())
                .idTipoprueba(e.getIdTipoprueba())
                .ubicacion(ubicacionDto)
                .estado(estadoDto)
                .tipoprueba(tipopruebaDto)
                .build();
    }

    @Transactional(readOnly = true)
    public List<PruebaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public PruebaDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public PruebaDTO create(PruebaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public PruebaDTO update(Integer id, PruebaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Prueba no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Prueba no encontrado con id: " + id));
        repository.deleteById(id);
    }

    @Transactional(readOnly = true)
    public List<PruebaDTO> findByIdAspirante(Integer idAspirante) {
        return entityListToDtoList(repository.findByIdAspirante(idAspirante));
    }

    public PruebaDTO edit(Integer id, String nombre, String descripcion, LocalDate fecha, LocalTime tiempo,
            Integer idTipoprueba, Integer idUbicacion) {
        PruebaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Prueba no encontrada con id: " + id));
        if (nombre != null) entity.setNombre(nombre);
        if (descripcion != null) entity.setDescripcion(descripcion);
        if (fecha != null) entity.setFecha(fecha);
        if (tiempo != null) entity.setTiempo(tiempo);
        if (idTipoprueba != null) entity.setIdTipoprueba(idTipoprueba);
        if (idUbicacion != null) entity.setIdUbicacion(idUbicacion);
        repository.save(entity);
        return repository.findById(id).map(this::entityToDto)
                .orElseThrow(() -> new RuntimeException("Prueba no encontrada con id: " + id));
    }

    public PruebaDTO changeEstado(Integer id, Integer idEstado, String expectedCurrentEstado) {
        PruebaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Prueba no encontrada con id: " + id));
        String estadoActual = entity.getEstado() != null ? entity.getEstado().getTipo() : "";
        if (!expectedCurrentEstado.equalsIgnoreCase(estadoActual)) {
            throw new RuntimeException(
                    "La prueba no está en estado '" + expectedCurrentEstado + "'. Estado actual: " + estadoActual);
        }
        entity.setIdEstado(idEstado);
        repository.save(entity);
        return repository.findById(id).map(this::entityToDto)
                .orElseThrow(() -> new RuntimeException("Prueba no encontrada con id: " + id));
    }

    public PruebaDTO changeEstadoWithMotivo(Integer id, Integer idEstado, String expectedCurrentEstado, String motivocambio) {
        PruebaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Prueba no encontrada con id: " + id));
        String estadoActual = entity.getEstado() != null ? entity.getEstado().getTipo() : "";
        if (!expectedCurrentEstado.equalsIgnoreCase(estadoActual)) {
            throw new RuntimeException(
                    "La prueba no está en estado '" + expectedCurrentEstado + "'. Estado actual: " + estadoActual);
        }
        entity.setIdEstado(idEstado);
        entity.setMotivocambio(motivocambio);
        repository.save(entity);
        return repository.findById(id).map(this::entityToDto)
                .orElseThrow(() -> new RuntimeException("Prueba no encontrada con id: " + id));
    }

    public PruebaDTO reschedule(Integer id, LocalDate fecha, LocalTime tiempo,
            Integer idTipoprueba, Integer idUbicacion) {
        PruebaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Prueba no encontrada con id: " + id));
        String estadoActual = entity.getEstado() != null ? entity.getEstado().getTipo() : "";
        if (!"SOLICITUD DE CAMBIO".equalsIgnoreCase(estadoActual)) {
            throw new IllegalStateException(
                    "La prueba no está en estado 'SOLICITUD DE CAMBIO'. Estado actual: " + estadoActual);
        }
        Integer idEstadoPendiente = estadoRepository
                .findByTipoIgnoreCaseAndEntidadIgnoreCase("PENDIENTE DE CONFIRMACION", "prueba")
                .orElseThrow(() -> new RuntimeException("Estado 'PENDIENTE DE CONFIRMACION' no encontrado para entidad 'prueba'"))
                .getId();
        entity.setFecha(fecha);
        entity.setTiempo(tiempo);
        entity.setIdTipoprueba(idTipoprueba);
        entity.setIdUbicacion(idUbicacion);
        entity.setIdEstado(idEstadoPendiente);
        entity.setMotivocambio(null);
        repository.save(entity);
        return repository.findById(id).map(this::entityToDto)
                .orElseThrow(() -> new RuntimeException("Prueba no encontrada con id: " + id));
    }
}
