/*
 * Created on 2026-05-18 ( 01:57:54 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.ResultadopruebaEntity;
import ufps.edu.co.persistence.repositories.ResultadopruebaRepository;
import ufps.edu.co.rest.dto.ResultadopruebaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Resultadoprueba" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class ResultadopruebaService extends GenericService<ResultadopruebaEntity, ResultadopruebaDTO> {

    @Autowired
    private ResultadopruebaRepository repository;

    public ResultadopruebaService() {
        super(ResultadopruebaEntity.class, ResultadopruebaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<ResultadopruebaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public ResultadopruebaDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public ResultadopruebaDTO create(ResultadopruebaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public ResultadopruebaDTO update(Integer id, ResultadopruebaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Resultadoprueba no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Resultadoprueba no encontrado con id: " + id));
        repository.deleteById(id);
    }
}