/*
 * Created on 2026-05-18 ( 01:57:55 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.SemestreEntity;
import ufps.edu.co.persistence.repositories.SemestreRepository;
import ufps.edu.co.rest.dto.EstadoDTO;
import ufps.edu.co.rest.dto.SemestreDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Semestre" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class SemestreService extends GenericService<SemestreEntity, SemestreDTO> {

    @Autowired
    private SemestreRepository repository;

    public SemestreService() {
        super(SemestreEntity.class, SemestreDTO.class);
    }

    @Override
    protected SemestreDTO entityToDto(SemestreEntity e) {
        EstadoDTO estadoDto = e.getEstado() != null ? EstadoDTO.builder()
                .id(e.getEstado().getId())
                .entidad(e.getEstado().getEntidad())
                .tipo(e.getEstado().getTipo())
                .build() : null;
        return SemestreDTO.builder()
                .id(e.getId())
                .nombre(e.getNombre())
                .fechaInicio(e.getFechaInicio())
                .fechaFin(e.getFechaFin())
                .idEstado(e.getIdEstado())
                .estado(estadoDto)
                .build();
    }

    @Transactional(readOnly = true)
    public List<SemestreDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public SemestreDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public SemestreDTO create(SemestreDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public SemestreDTO update(Integer id, SemestreDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Semestre no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Semestre no encontrado con id: " + id));
        repository.deleteById(id);
    }
}
