/*
 * Created on 2026-05-14 ( 22:38:05 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.TipovinculacionEntity;
import ufps.edu.co.persistence.repositories.TipovinculacionRepository;
import ufps.edu.co.rest.dto.TipovinculacionDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Tipovinculacion" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class TipovinculacionService extends GenericService<TipovinculacionEntity, TipovinculacionDTO> {

    @Autowired
    private TipovinculacionRepository repository;

    public TipovinculacionService() {
        super(TipovinculacionEntity.class, TipovinculacionDTO.class);
    }

    @Transactional(readOnly = true)
    public List<TipovinculacionDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public TipovinculacionDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public TipovinculacionDTO create(TipovinculacionDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public TipovinculacionDTO update(Integer id, TipovinculacionDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Tipovinculacion no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Tipovinculacion no encontrado con id: " + id));
        repository.deleteById(id);
    }
}