/*
 * Created on 2026-05-14 ( 22:04:37 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.TipopagoEntity;
import ufps.edu.co.persistence.repositories.TipopagoRepository;
import ufps.edu.co.rest.dto.TipopagoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Tipopago" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class TipopagoService extends GenericService<TipopagoEntity, TipopagoDTO> {

    @Autowired
    private TipopagoRepository repository;

    public TipopagoService() {
        super(TipopagoEntity.class, TipopagoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<TipopagoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public TipopagoDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public TipopagoDTO create(TipopagoDTO dto) {
        if (repository.existsById(dto.getId())) {
            throw new RuntimeException("Tipopago ya existe con id: " + dto.getId());
        }
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public TipopagoDTO update(Integer id, TipopagoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Tipopago no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Tipopago no encontrado con id: " + id));
        repository.deleteById(id);
    }
}