/*
 * Created on 2026-05-18 ( 01:57:55 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.TiporegistroEntity;
import ufps.edu.co.persistence.repositories.TiporegistroRepository;
import ufps.edu.co.rest.dto.TiporegistroDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Tiporegistro" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class TiporegistroService extends GenericService<TiporegistroEntity, TiporegistroDTO> {

    @Autowired
    private TiporegistroRepository repository;

    public TiporegistroService() {
        super(TiporegistroEntity.class, TiporegistroDTO.class);
    }

    @Transactional(readOnly = true)
    public List<TiporegistroDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public TiporegistroDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public TiporegistroDTO create(TiporegistroDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public TiporegistroDTO update(Integer id, TiporegistroDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Tiporegistro no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Tiporegistro no encontrado con id: " + id));
        repository.deleteById(id);
    }
}