# Load environment vars from either current execution dir or repo root.
spring.config.import=optional:file:.env.properties,optional:file:../.env.properties

# Server configuration
spring.application.name=${APP_NAME}

# Global context path for all REST endpoints
server.servlet.context-path=${APP_PREFIX}

# API REST prefixes
api.rest.prefix=/api/dev/endpoint
api.rest.cases-prefix=/api/application

# Required module load markers (fail-fast if missing)
app.module.name.api-base=${APP_MODULE_NAME_API_BASE}
app.module.name.api-core=${APP_MODULE_NAME_API_CORE}
app.module.name.api-rest=${APP_MODULE_NAME_API_REST}

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.jpa.database-platform=${DB_DIALECT}
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Configuration for API documentation
springdoc.api-docs.enabled=${ENABLE_API_DOCS}
springdoc.swagger-ui.enabled=${ENABLE_SWAGGER_UI}
springdoc.api-docs.path=${SWAGGER_API_DOCS_PATH}
springdoc.swagger-ui.path=${SWAGGER_UI_PATH}


# logging config
# # # logging.level.root=INFO
# # # logging.level.ufps.edu.co=DEBUG
# # # logging.level.ufps.edu.co.persistence=DEBUG
# # # logging.level.ufps.edu.co.rest.controllers=DEBUG
# # # logging.level.ufps.edu.co.rest.services=DEBUG


