/*
 * Created on 2026-04-27 ( 00:27:31 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.controllers.rest;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import ufps.edu.co.processor.DepartamentoProcessor;
import ufps.edu.co.records.input.DepartamentoInput.DEPARTAMENTO_CREATE;
import ufps.edu.co.records.input.DepartamentoInput.DEPARTAMENTO_FIND;
import ufps.edu.co.records.output.DepartamentoOutput;

@RestController
@RequestMapping(value = "/departamento", produces = MediaType.APPLICATION_JSON_VALUE)
public class DepartamentoRestController {

    @Autowired
    private DepartamentoProcessor processor;

    @GetMapping("/listall")
    public ResponseEntity<List<DepartamentoOutput>> findAll() {
        List<DepartamentoOutput> list = processor.findAll();
        return ResponseEntity.ok(list); // 200 OK
    }

    @GetMapping("/list")
    public ResponseEntity<DepartamentoOutput> findById(@RequestBody DEPARTAMENTO_FIND request) {
        DepartamentoOutput departamentoOutput = processor.findById(request);
        if ( departamentoOutput != null ) {
            return ResponseEntity.ok(departamentoOutput); // 200 OK
        } else {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }

    /**
     * Create
     *
     * @param departamentoDTO
     * @return 201 creado o 409 si ya existe
     */
    @PostMapping("/create")
    public ResponseEntity<DepartamentoOutput> create(@RequestBody DEPARTAMENTO_CREATE request) {
        DepartamentoOutput output = processor.create(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(output);
    }

    /**
     * Update if exists
     *
     * @param id
     * @param departamentoDTO
     * @return 200 con DTO actualizado o 404 si no existe
     */
    // @PutMapping("/{id}")
    // public ResponseEntity<DepartamentoDTO> update(@RequestBody int id, @RequestBody DepartamentoDTO departamentoDTO) {
    //     // try {
    //     //     DepartamentoDTO updated = service.update(id, departamentoDTO);
    //     //     return ResponseEntity.ok(updated); // 200 OK
    //     // } catch (RuntimeException e) {
    //     //     return ResponseEntity.notFound().build(); // 404 Not found
    //     // }
    //     return null;
    // }

    /**
     * Delete by PK
     *
     * @param id
     * @return 204 eliminado o 404 si no existe
     */
    // @DeleteMapping("/{id}")
    // public ResponseEntity<Void> deleteById(@RequestBody int id) {
    //     // try {
    //     //     service.deleteById(id);
    //     //     return ResponseEntity.noContent().build(); // 204 No content
    //     // } catch (RuntimeException e) {
    //     //     return ResponseEntity.notFound().build(); // 404 Not found
    //     // }
    //     return null;
    // }
}