/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDate;
import java.util.List;


/**
 * JPA entity class for "Aspirante"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "aspirante")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AspiranteEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="primer_nombre", nullable=false, length=50)
    private String     primerNombre ;

    @Column(name="segundo_nombre", length=50)
    private String     segundoNombre ;

    @Column(name="primer_apellido", nullable=false, length=50)
    private String     primerApellido ;

    @Column(name="segundo_apellido", length=50)
    private String     segundoApellido ;

    @Column(name="id_genero", nullable=false)
    private int        idGenero ;

    @Column(name="id_residencia", nullable=false)
    private int        idResidencia ;

    @Column(name="telefono", length=20)
    private String     telefono ;

    @Column(name="celular", nullable=false, length=20)
    private String     celular ;

    @Column(name="correo_electronico", nullable=false, length=255)
    private String     correoElectronico ;

    @Column(name="fecha_nacimiento", nullable=false)
    private LocalDate  fechaNacimiento ;

    @Column(name="id_oferta_academica", nullable=false)
    private int        idOfertaAcademica ;

    @Column(name="id_estado_aspirante")
    private Integer    idEstadoAspirante ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_genero", referencedColumnName="id", insertable=false, updatable=false)
    private GeneroEntity     genero ; 

    @ManyToOne
    @JoinColumn(name="id_residencia", referencedColumnName="id", insertable=false, updatable=false)
    private ResidenciaEntity residencia ; 

    @ManyToOne
    @JoinColumn(name="id_oferta_academica", referencedColumnName="id", insertable=false, updatable=false)
    private OfertaAcademicaEntity ofertaacademica ; 

    @ManyToOne
    @JoinColumn(name="id_estado_aspirante", referencedColumnName="id", insertable=false, updatable=false)
    private EstadoAspiranteEntity estadoaspirante ; 

    @OneToMany(mappedBy="aspirante")
    private List<CorreccionEntity> correccionList ; 

    @OneToMany(mappedBy="aspirante")
    private List<DocumentoEntity> documentoList ; 

    @OneToMany(mappedBy="aspirante")
    private List<DocumentoIdentidadEntity> documentoidentidadList ; 

    @OneToMany(mappedBy="aspirante")
    private List<EtapaCompletadaEntity> etapacompletadaList ; 

    @OneToMany(mappedBy="aspirante")
    private List<TituloEntity> tituloList ; 

    @OneToMany(mappedBy="aspirante")
    private List<UsuarioAspiranteEntity> usuarioaspiranteList ; 

}
