/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * JPA entity class for "CambioDocumento"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "cambio_documento")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CambioDocumentoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="id_documento_cambiado", nullable=false)
    private int        idDocumentoCambiado ;

    @Column(name="id_documento_actual", nullable=false)
    private int        idDocumentoActual ;

    @Column(name="motivo_cambio", nullable=false, length=65535)
    private String     motivoCambio ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_documento_cambiado", referencedColumnName="id", insertable=false, updatable=false)
    private DocumentoEntity  documento ; 

    @ManyToOne
    @JoinColumn(name="id_documento_actual", referencedColumnName="id", insertable=false, updatable=false)
    private DocumentoEntity  documento2 ; 

}
