/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDateTime;


/**
 * JPA entity class for "Correccion"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "correccion")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CorreccionEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="motivo_correccion", nullable=false, length=65535)
    private String     motivoCorreccion ;

    @Column(name="fecha_solicitud", nullable=false)
    private LocalDateTime fechaSolicitud ;

    @Column(name="fecha_limite", nullable=false)
    private LocalDateTime fechaLimite ;

    @Column(name="id_documento", nullable=false)
    private int        idDocumento ;

    @Column(name="id_aspirante", nullable=false)
    private int        idAspirante ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_documento", referencedColumnName="id", insertable=false, updatable=false)
    private DocumentoEntity  documento ; 

    @ManyToOne
    @JoinColumn(name="id_aspirante", referencedColumnName="id", insertable=false, updatable=false)
    private AspiranteEntity  aspirante ; 

}
