/*
 * Created on 2026-04-30 ( 19:08:00 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Departamento"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "departamento")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DepartamentoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="nombre", nullable=false, length=100)
    private String     nombre ;

    @Column(name="id_pais", nullable=false)
    private int        idPais ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_pais", referencedColumnName="id", insertable=false, updatable=false)
    private PaisEntity       pais ; 

    @OneToMany(mappedBy="departamento")
    private List<MunicipioEntity> municipioList ; 

}
