/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDateTime;
import java.util.List;


/**
 * JPA entity class for "Documento"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "documento")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DocumentoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="id_aspirante", nullable=false)
    private int        idAspirante ;

    @Column(name="id_tipo_documento", nullable=false)
    private int        idTipoDocumento ;

    @Column(name="id_estado_documento", nullable=false)
    private int        idEstadoDocumento ;

    @Column(name="id_administrativo_reviso")
    private Integer    idAdministrativoReviso ;

    @Column(name="fecha_maxima_cargue", nullable=false)
    private LocalDateTime fechaMaximaCargue ;

    @Column(name="fecha_cargue", nullable=false)
    private LocalDateTime fechaCargue ;

    @Column(name="url", nullable=false, length=255)
    private String     url ;

    @Column(name="key_file", nullable=false, length=255)
    private String     keyFile ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany
    private List<CambioDocumentoEntity> cambiodocumentoList ; 

    @OneToMany
    private List<CambioDocumentoEntity> cambiodocumentoList2 ; 

    @OneToMany(mappedBy="documento")
    private List<CorreccionEntity> correccionList ; 

    @ManyToOne
    @JoinColumn(name="id_aspirante", referencedColumnName="id", insertable=false, updatable=false)
    private AspiranteEntity  aspirante ; 

    @ManyToOne
    @JoinColumn(name="id_tipo_documento", referencedColumnName="id", insertable=false, updatable=false)
    private TipoDocumentoEntity tipodocumento ; 

    @ManyToOne
    @JoinColumn(name="id_estado_documento", referencedColumnName="id", insertable=false, updatable=false)
    private EstadoDocumentoEntity estadodocumento ; 

    @ManyToOne
    @JoinColumn(name="id_administrativo_reviso", referencedColumnName="id", insertable=false, updatable=false)
    private PersonalAdministrativoEntity personaladministrativo ; 

    @OneToMany(mappedBy="documento")
    private List<HistorialEstadoDocumentoEntity> historialestadodocumentoList ; 

}
