/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * JPA entity class for "DocumentoRequeridoOferta"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "documento_requerido_oferta")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DocumentoRequeridoOfertaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="id_oferta_academica", nullable=false)
    private int        idOfertaAcademica ;

    @Column(name="id_tipo_documento", nullable=false)
    private int        idTipoDocumento ;

    @Column(name="obligatorio", nullable=false)
    private boolean    obligatorio ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_oferta_academica", referencedColumnName="id", insertable=false, updatable=false)
    private OfertaAcademicaEntity ofertaacademica ; 

    @ManyToOne
    @JoinColumn(name="id_tipo_documento", referencedColumnName="id", insertable=false, updatable=false)
    private TipoDocumentoEntity tipodocumento ; 

}
