/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * JPA entity class for "DocumentoIdentidad"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "documento_identidad")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DocumentoIdentidadEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="numero_documento", nullable=false, length=20)
    private String     numeroDocumento ;

    @Column(name="id_aspirante", nullable=false)
    private int        idAspirante ;

    @Column(name="id_tipo_documento", nullable=false)
    private int        idTipoDocumento ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_aspirante", referencedColumnName="id", insertable=false, updatable=false)
    private AspiranteEntity  aspirante ; 

    @ManyToOne
    @JoinColumn(name="id_tipo_documento", referencedColumnName="id", insertable=false, updatable=false)
    private TipoDocumentoEntity tipodocumento ; 

}
