/*
 * Created on 2026-04-24 ( 22:23:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDateTime;


/**
 * JPA entity class for "EtapaCompletada"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "etapa_completada")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EtapaCompletadaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="id_aspirante", nullable=false)
    private int        idAspirante ;

    @Column(name="id_tipo_etapa", nullable=false)
    private int        idTipoEtapa ;

    @Column(name="fecha", nullable=false)
    private LocalDateTime fecha ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_aspirante", referencedColumnName="id", insertable=false, updatable=false)
    private AspiranteEntity  aspirante ; 

    @ManyToOne
    @JoinColumn(name="id_tipo_etapa", referencedColumnName="id", insertable=false, updatable=false)
    private TipoEtapaEntity  tipoetapa ; 

}
