/*
 * Created on 2026-04-24 ( 22:23:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDateTime;


/**
 * JPA entity class for "HistorialEstadoDocumento"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "historial_estado_documento")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class HistorialEstadoDocumentoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="id_documento", nullable=false)
    private int        idDocumento ;

    @Column(name="id_estado_anterior", nullable=false)
    private int        idEstadoAnterior ;

    @Column(name="id_estado_nuevo", nullable=false)
    private int        idEstadoNuevo ;

    @Column(name="id_administrativo")
    private Integer    idAdministrativo ;

    @Column(name="fecha_cambio", nullable=false)
    private LocalDateTime fechaCambio ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_documento", referencedColumnName="id", insertable=false, updatable=false)
    private DocumentoEntity  documento ; 

    @ManyToOne
    @JoinColumn(name="id_estado_anterior", referencedColumnName="id", insertable=false, updatable=false)
    private EstadoDocumentoEntity estadodocumento ; 

    @ManyToOne
    @JoinColumn(name="id_estado_nuevo", referencedColumnName="id", insertable=false, updatable=false)
    private EstadoDocumentoEntity estadodocumento2 ; 

    @ManyToOne
    @JoinColumn(name="id_administrativo", referencedColumnName="id", insertable=false, updatable=false)
    private PersonalAdministrativoEntity personaladministrativo ; 

}
