/*
 * Created on 2026-04-24 ( 22:23:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "OfertaAcademica"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "oferta_academica")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OfertaAcademicaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="id_programa", nullable=false)
    private int        idPrograma ;

    @Column(name="id_cohorte", nullable=false)
    private int        idCohorte ;

    @Column(name="cupos", nullable=false)
    private int        cupos ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="ofertaacademica")
    private List<AspiranteEntity> aspiranteList ; 

    @OneToMany(mappedBy="ofertaacademica")
    private List<DocumentoRequeridoOfertaEntity> documentorequeridoofertaList ; 

    @ManyToOne
    @JoinColumn(name="id_programa", referencedColumnName="id", insertable=false, updatable=false)
    private ProgramaPosgradoEntity programaposgrado ; 

    @ManyToOne
    @JoinColumn(name="id_cohorte", referencedColumnName="id", insertable=false, updatable=false)
    private CohorteEntity    cohorte ; 

}
