/*
 * Created on 2026-05-01 ( 01:00:24 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * JPA entity class for "Ofertaacademica"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "ofertaacademica")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OfertaacademicaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="encuentros", length=65535)
    private String     encuentros ;

    @Column(name="cupos", nullable=false)
    private int        cupos ;

    @Column(name="id_programa", nullable=false)
    private int        idPrograma ;

    @Column(name="id_modalidad", nullable=false)
    private int        idModalidad ;

    @Column(name="id_jornada", nullable=false)
    private int        idJornada ;

    @Column(name="id_cohorte", nullable=false)
    private int        idCohorte ;

    @Column(name="id_plazo", nullable=false)
    private int        idPlazo ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_programa", referencedColumnName="id", insertable=false, updatable=false)
    private ProgramaEntity   programa ; 

    @ManyToOne
    @JoinColumn(name="id_modalidad", referencedColumnName="id", insertable=false, updatable=false)
    private ModalidadEntity  modalidad ; 

    @ManyToOne
    @JoinColumn(name="id_jornada", referencedColumnName="id", insertable=false, updatable=false)
    private JornadaEntity    jornada ; 

    @ManyToOne
    @JoinColumn(name="id_cohorte", referencedColumnName="id", insertable=false, updatable=false)
    private CohorteEntity    cohorte ; 

    @ManyToOne
    @JoinColumn(name="id_plazo", referencedColumnName="id", insertable=false, updatable=false)
    private PlazoEntity      plazo ; 

}
