/*
 * Created on 2026-04-24 ( 22:23:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "PersonalAdministrativo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "personal_administrativo")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PersonalAdministrativoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="nombre", nullable=false, length=100)
    private String     nombre ;

    @Column(name="correo", nullable=false, length=100)
    private String     correo ;

    @Column(name="contraseña", nullable=false, length=100)
    private String     contraseña ;

    @Column(name="id_cargo", nullable=false)
    private int        idCargo ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="personaladministrativo")
    private List<DocumentoEntity> documentoList ; 

    @OneToMany(mappedBy="personaladministrativo")
    private List<HistorialEstadoDocumentoEntity> historialestadodocumentoList ; 

    @ManyToOne
    @JoinColumn(name="id_cargo", referencedColumnName="id", insertable=false, updatable=false)
    private CargoEntity      cargo ; 

}
