/*
 * Created on 2026-04-30 ( 18:48:52 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDate;
import java.util.List;


/**
 * JPA entity class for "Plazo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "plazo")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PlazoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="fechainicio", nullable=false)
    private LocalDate  fechainicio ;

    @Column(name="fechafin", nullable=false)
    private LocalDate  fechafin ;

    @Column(name="id_tipoplazo", nullable=false)
    private int        idTipoplazo ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="plazo")
    private List<DocumentoEntity> documentoList ; 

    @OneToMany(mappedBy="plazo")
    private List<OfertaacademicaEntity> ofertaacademicaList ; 

    @ManyToOne
    @JoinColumn(name="id_tipoplazo", referencedColumnName="id", insertable=false, updatable=false)
    private TipoplazoEntity  tipoplazo ; 

}
