/*
 * Created on 2026-04-24 ( 22:23:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "ProgramaPosgrado"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "programa_posgrado")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ProgramaPosgradoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="codigo", nullable=false)
    private int        codigo ;

    @Column(name="nombre_programa", nullable=false, length=255)
    private String     nombrePrograma ;

    @Column(name="duracion_programa_semestres", nullable=false)
    private short      duracionProgramaSemestres ;

    @Column(name="correo_programa", nullable=false, length=255)
    private String     correoPrograma ;

    @Column(name="nombre_director", length=255)
    private String     nombreDirector ;

    @Column(name="registro_snies", length=10)
    private String     registroSnies ;

    @Column(name="id_modalidad", nullable=false)
    private int        idModalidad ;

    @Column(name="id_facultad", nullable=false)
    private int        idFacultad ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="programaposgrado")
    private List<OfertaAcademicaEntity> ofertaacademicaList ; 

    @ManyToOne
    @JoinColumn(name="id_modalidad", referencedColumnName="id", insertable=false, updatable=false)
    private ModalidadEntity  modalidad ; 

    @ManyToOne
    @JoinColumn(name="id_facultad", referencedColumnName="id", insertable=false, updatable=false)
    private FacultadEntity   facultad ; 

}
