/*
 * Created on 2026-04-24 ( 22:23:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Residencia"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "residencia")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ResidenciaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="id_pais", nullable=false)
    private int        idPais ;

    @Column(name="id_departamento")
    private Integer    idDepartamento ;

    @Column(name="id_municipio")
    private Integer    idMunicipio ;

    @Column(name="direccion", nullable=false, length=65535)
    private String     direccion ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="residencia")
    private List<AspiranteEntity> aspiranteList ; 

    @ManyToOne
    @JoinColumn(name="id_pais", referencedColumnName="id", insertable=false, updatable=false)
    private PaisEntity       pais ; 

    @ManyToOne
    @JoinColumn(name="id_departamento", referencedColumnName="id", insertable=false, updatable=false)
    private DepartamentoEntity departamento ; 

    @ManyToOne
    @JoinColumn(name="id_municipio", referencedColumnName="id", insertable=false, updatable=false)
    private MunicipioEntity  municipio ; 

}
