/*
 * Created on 2026-04-24 ( 22:23:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "TipoDocumento"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tipo_documento")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TipoDocumentoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="nombre", nullable=false, length=255)
    private String     nombre ;

    @Column(name="descripcion", length=255)
    private String     descripcion ;

    @Column(name="formato", length=30)
    private String     formato ;

    @Column(name="url_formato", length=255)
    private String     urlFormato ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="tipodocumento")
    private List<DocumentoEntity> documentoList ; 

    @OneToMany(mappedBy="tipodocumento")
    private List<DocumentoIdentidadEntity> documentoidentidadList ; 

    @OneToMany(mappedBy="tipodocumento")
    private List<DocumentoRequeridoOfertaEntity> documentorequeridoofertaList ; 

}
