/*
 * Created on 2026-04-24 ( 22:23:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "TipoTitulo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "tipo_titulo")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TipoTituloEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="nombre", nullable=false, length=50)
    private String     nombre ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="tipotitulo")
    private List<TituloEntity> tituloList ; 

}
