/*
 * Created on 2026-04-24 ( 22:23:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Usuario"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "usuario")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UsuarioEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- OTHER DATA FIELDS 
    @Column(name="correo", nullable=false, length=255)
    private String     correo ;

    @Column(name="contrasena", nullable=false, length=255)
    private String     contrasena ;

    @Column(name="activo")
    private Boolean    activo ;

    @Column(name="id_rol", nullable=false)
    private int        idRol ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_rol", referencedColumnName="id", insertable=false, updatable=false)
    private RolEntity        rol ; 

    @OneToMany(mappedBy="usuario")
    private List<UsuarioAspiranteEntity> usuarioaspiranteList ; 

}
